### PR TITLE
CL: disable chunking until further notice

### LINKED ISSUE #2559: Chunking for NVIDIA cards
Ubuntu15.04, Nvidia 660ti 2GB memory, but max memory allocation (geth gpuinfo)or(clinfo) is 500MB. 
Is it possible to mine with this card?
How can I split up the DAG?

john@alderhillone:~$ ethminer -G -F http://127.0.0.1:8545
[OPENCL]:Found suitable OpenCL device [GeForce GTX 660 Ti] with 2147155968 bytes of GPU memory
miner 23:35:04|ethminer Getting work package...

ℹ 23:35:09|ethminer Loading full DAG of seedhash: #290decd9…
miner 23:35:10|ethminer Getting work package...
miner 23:35:10|ethminer Grabbing DAG for #5a46dd85…
ℹ 23:35:14|ethminer Full DAG loaded
miner 23:35:21|ethminer Got work package:
miner 23:35:21|ethminer Header-hash: c21c407788fcbfac56d7157526e7a6455ec69e265ec74fe4d2d60f0803c1ac2c
miner 23:35:21|ethminer Seedhash: 5a46dd85298b0beff65ccf3006c4b5d2f7fa6ca8a5885a7f2132714fe7a48602
miner 23:35:21|ethminer Target: 000000002bf83e1cdec8746c78083e1637e163db9a5e141cd3a72a4c5c6c9216
miner 23:35:21|ethminer Mining on PoWhash #c21c4077… : 0 H/s = 0 hashes / 0.5 s
miner 23:35:21|ethminer Got work package:
miner 23:35:21|ethminer Header-hash: 36b08af8fcfc0c408110b59cd1102cfa781c5b2c26a80e1ee382f0f869e0acd3
miner 23:35:21|ethminer Seedhash: 5a46dd85298b0beff65ccf3006c4b5d2f7fa6ca8a5885a7f2132714fe7a48602
miner 23:35:21|ethminer Target: 000000002bf2bfc4ea19045deb590d852d521f098972df68b7edcaf4b110ccb4
miner 23:35:22|ethminer Mining on PoWhash #36b08af8… : 0 H/s = 0 hashes / 0.5 s
miner 23:35:22|ethminer Mining on PoWhash #36b08af8… : 0 H/s = 0 hashes / 1 s
miner 23:35:23|ethminer Mining on PoWhash #36b08af8… : 0 H/s = 0 hashes / 1.501 s
miner 23:35:23|ethminer Mining on PoWhash #36b08af8… : 0 H/s = 0 hashes / 2.002 s
miner 23:35:24|ethminer Mining on PoWhash #36b08af8… : 0 H/s = 0 hashes / 2.503 s
miner 23:35:24|ethminer Mining on PoWhash #36b08af8… : 0 H/s = 0 hashes / 3.004 s
miner 23:35:25|ethminer Mining on PoWhash #36b08af8… : 0 H/s = 0 hashes / 3.504 s

Output from geth gpuinfo:

=============================================
============ OpenCL Device Info =============
=============================================
Platform id 0
Platform Name NVIDIA CUDA
Platform Vendor NVIDIA Corporation
Platform Version OpenCL 1.1 CUDA 7.0.35
Platform Extensions cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts
Platform Profile FULL_PROFILE

Device OpenCL id 0
Device id for mining 0
Device Name GeForce GTX 660 Ti
Vendor NVIDIA Corporation
Version OpenCL 1.1 CUDA
Driver version 346.59
Address bits 32
Max clock freq 980
Global mem size 2147155968
Max constant buffer size 65536
Max mem alloc size 536788992
Max compute units 7
Max work group size 1024
Max work item sizes [1024 1024 64]
=============================================
Found 1 devices. Benchmark first GPU: geth gpubench 0
Mine using all GPUs: geth --minegpu 0
You may also need to enable chunking: --gpuchunks

### PR DESCRIPTION
**Pull request by LefterisJP**
Probably fixes #2559 even though chunking is not stable at the moment.

### CODE REVIEW

**Comment by subtly** [comment]
Chunking doesn't work. It needs to be disabled until someone can fix it.

**Comment by LefterisJP** [comment]
I see two options here. 

1. We totally disable chunking for now.
2. We let it be there with an understanding that it may not work properly but it's our best effort to support those cards that can't allocate the DAG in one big chunk. 

I did test that this does not break our existing functionality both on a chunking and on a non chunking GPU miner. I will also ask the OP if he can test this PR.
If we go with the second option, this PR would allow people who fail on `clEnqueueWriteBuffer()` to at least try chunking rather than fail on it due to memory allocation errors.

**Comment by mooneyj** [comment]
using git fetch origin refs/pull/2575/head:2575

Chunking is activated, but still;
```
[OPENCL]:clEnqueueMapBuffer(-4)
[OPENCL]:clEnqueueWriteBuffer(-38)
```
full output
```
john@alderhillone:~/ethereum/cpp-ethereum/build$ ./ethminer/ethminer -G -M
[OPENCL]:Found suitable OpenCL device [GeForce GTX 660 Ti] with 2147155968 bytes of GPU memory
Benchmarking on platform: GPU
Preparing DAG...
Warming up...
  ℹ  23:46:03|gpuminer0  workLoop 0 #00000000… #00000000…
  ℹ  23:46:03|gpuminer0  Initialising miner...
[OPENCL]:Using platform: NVIDIA CUDA
[OPENCL]:Using device: GeForce GTX 660 Ti(OpenCL 1.1 CUDA)
[OPENCL]:Printing program log
[OPENCL]:

**Comment by LefterisJP** [comment]
I see. Thanks for trying it out. It's quite possible then that with your GPU and our current implementation mining won't be possible for you.

After you trying out this PR I am lead to believe that your GPU has such a small `MAX_ALLOCATEABLE_MEMORY` limit (500MB?) that even dividing the latest testnet DAG size by 4 does not cut it for you. Shows yet another problem of our current "chunking" implementation. In a perfect implementation the chunking would divide the DAG in enough pieces depending on the `MAX_ALLOCATEABLE_MEMORY` of the respective GPU.

But we currently don't have such an implementation. It's a backlog TODO after the release.

**Comment by mooneyj** [comment]
That's a shame. Thanks for your help though.

**Comment by LefterisJP** [comment]
Using this PR to disable chunking in general since we decided not to support it, at least for the frontier release. Look below for how it looks on a pc that needs to chunk:

```
[OPENCL]:Using device: Pitcairn(OpenCL 1.2 AMD-APP (1445.5))
  ◇  10:00:04|eth  Farm::setWork()
> [OPENCL]:Printing program log
[OPENCL]:LOOP UNROLL: pragma unroll (line 300)
    Unrolled as requested!
LOOP UNROLL: pragma unroll (line 266)
    Unrolled as requested!
LOOP UNROLL: pragma unroll (line 361)
    Unrolled as requested!
LOOP UNROLL: pragma unroll (line 361)
    Unrolled as requested!

[OPENCL]:Creating one big buffer for the DAG
[OPENCL]:Allocating/mapping single buffer failed with: clCreateBuffer(-61). GPU can't allocate the DAG in a single chunk. Bailing.
[OPENCL]:clEnqueueWriteBuffer(-38)
⧎ ℹ  10:00:07|p2p|b09f21bb…|Geth/v1.0.0/linux/go1.4.2  DISABLE: Disabling capability ' eth '. Reason: Invalid genesis hash
⧎ ℹ  10:00:08|p2p|4641099f…|Geth/v0.9.39/linux/go1.4.2  DISABLE: Disabling capability ' eth '. Reason: Invalid network identifier.
⧎ ℹ  10:00:15|p2p|1d719beb…|Geth/v0.9.38-98f4c936/linux/go1.4.2  NewHash: #96c837b1…
⧎ ℹ  10:00:15|p2p|93a91455…|Geth/v0.9.38/linux/go1.4.2  NewBlock: #96c837b1…
⧎ ℹ  10:00:19|p2p|93a91455…|Geth/v0.9.38/linux/go1.4.2  NewHash: #42b0e597…
```

Should we instead exit the program with an error or is this sufficient?

**Comment by gavofyork** [comment]
fine as that, i think.

**Comment by LefterisJP** [comment]
All right, then review/merge at your convenience.

**Comment by gregbkr** [comment]
Hello, I am reading around and try to see if there is one version allowing chunking DAG (for amd HD 6900 series (2GB), where catalyst drive hardfix CL_DEVICE_MAX_MEM_ALLOC_SIZE to 500MB). Thank you for your help!

**Comment by bobsummerwill** [comment]
I don't believe so, @gregbkr, though somebody else raised the question a month or so back.

From what I recall, this code is still disabled, because it was unreliable, and of interest/benefit only to a small subset of people.

If you have the time and ability to bring it to a usable state yourself, then maybe it could make a comeback?

**Pull request merged**
