### PR TITLE
fixed missing windows colors defines

### PR DESCRIPTION
**Pull request by debris**

### CODE REVIEW

**Comment by chriseth** [comment]
I think this file should not be in libdevcore. Otherwise it looks good :-)

**Comment by chriseth** [comment]
Ah, it does not, `EthOrage` is missing.

**Comment by chriseth** [comment]
And another comment: What about using a macro for the two choices a la
```
#define EthOrage EthColor("\magicescapeforLinux", "\magicescapeforWindows")

**Comment by debris** [comment]
I don't know if using escapes on windows is so simple...
According to [this stackoverflow](http://stackoverflow.com/questions/16755142/how-to-make-win32-console-recognize-ansi-vt100-escape-sequences) answer it is not. But there is [C library](https://github.com/adoxa/ansicon), we might want to use.

**Comment by gavofyork** [comment]
someone else was already on the job...

**Pull request closed without merging**
