### PR TITLE
Add a JS console command for exiting the client

### PR DESCRIPTION
**Pull request by LefterisJP**
The function is web3.admin.eth.exit()

### CODE REVIEW

**Comment by gavofyork** [comment]
rebase. i guess you can remove `quit` functionality.

**Comment by LefterisJP** [comment]
Rebased

**Comment by LefterisJP** [comment]
Build error seems to be unrelated:

```
SyntaxError: Unexpected end of input
/slave/build-cpp-ethereum-evmjit-pr/build/libsolidity/Parser.cpp(164): fatal error in "dev::solidity::ASTPointer<dev::solidity::ContractDefinition> dev::solidity::Parser::parseContractDefinition()": std::exception: std::exception
/slave/build-cpp-ethereum-evmjit-pr/build/test/libsolidity/SolidityNameAndTypeResolution.cpp(1911): last checkpoint
```

**Comment by LefterisJP** [comment]
#2785 should fix the build errors

**Comment by LefterisJP** [comment]
Rebased again to see green builds

**Pull request merged**
