### PR TITLE
Chunk upload of DAG for older AMD cards (OpenCL < 2.0)

### LINKED ISSUE #2010: CL_INVALID_BUFFER_SIZE and CL_INVALID_MEM_OBJECT for OpenCL 1.2 cards
I'm getting mining errors:

```
gpuminer0  Error GPU mining: clCreateBuffer ( -61 ) // CL_INVALID_BUFFER_SIZE
gpuminer0  workLoop .....
gpuminer0  Error GPU mining: clEnqueueWriteBuffer ( -38 ) // CL_INVALID_MEM_OBJECT
```

This has been confirmed on both Radeon Tahiti and Cayman platforms. At least in the Cayman case, this is a dual-core card. But I know of other dual-core cards that work, for example 290x2, so it is maybe the OpenCL 1.2 that is the issue - or the combination of the two.

Does anyone know of things to try? I'm happy playing around with the code.

See also #1982

### PR DESCRIPTION
**Pull request by kejace**
This fixes #2010 and potentially #1982. All credit to @sontol for writing the updated code. I just made an ugly merge.

How to use: There's a `#define chunks` at the top. Put it to true and re-compile. Then copy the *.cl file to your binary folder.

`chunks` should probably be merged into the `CL_VERSION_1_2` flag.

The updated .cl file has code duplicated as `...hash_chunks()` etc. This can be refactored, but I kept it for more convenient compilation.

### CODE REVIEW

**Comment by subtly** [comment]
Is the 512MB a parameter which can be queried from opencl?

**Comment by gavofyork** [comment]
@LefterisJP please take a look and refactor as required

**Comment by LefterisJP** [comment]
Will do, but can't "properly" test since I have no such AMD card.

**Comment by Gustav-Simonsson** [comment]
@subtly The max allocation size for a device can be queried with https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clGetDeviceInfo.html  and the  CL_DEVICE_MAX_MEM_ALLOC_SIZE 
@LefterisJP suggested we can use this to calculate optimal chunk number.

**Pull request merged**
