### PR TITLE
Fix ECIES vulnerability

### PR DESCRIPTION
**Pull request by arkpar**
AES IV should be random bytes, not just zeroes.

### CODE REVIEW

**Comment by chriseth** [comment]
Thanks!

**Comment by chriseth** [comment]
@winsvega can you please do some manual testing of this?

**Comment by bobsummerwill** [comment]
Hi, @arkpar, by the way!   Great to see you here :-)    And thanks for the PR.

**Comment by attritionorg** [comment]
Apologies for the late question. Was this a vulnerability in Crypto++ (https://github.com/weidai11/cryptopp/), or the specific implementation in cpp-ethereum?

**Comment by attritionorg** [comment]
Or @chriseth, can you answer perhaps? Thanks!

**Comment by arkpar** [comment]
This was an issue with cpp-ethereum, not Crypto++

**Pull request merged**
