### PR TITLE
Remove obsolete framing support from devp2p

### PR DESCRIPTION
**Pull request by gumb0**

### CODE REVIEW

**Comment by chfast** [comment]
I love it, but some unused params were left. See build errors.

**Comment by gumb0** [comment]
Yeah, I continue to delete even more stuff

**Comment by pirapira** [comment]
https://travis-ci.org/ethereum/cpp-ethereum/jobs/287108751
```
unknown location(0): fatal error: in "GeneralStateTests/stRandom": signal: illegal operand; address of failing instruction: 0x00ba7d53

/home/travis/build/ethereum/cpp-ethereum/test/tools/libtesteth/ImportTest.cpp(211): last checkpoint
```
?

**Comment by gumb0** [comment]
Well it shouldn't use any devp2p... I'll try to restart it

**Comment by gumb0** [comment]
It disappeared after 2nd restart

**Pull request merged**
