### PR TITLE
Thawing

### PR DESCRIPTION
**Pull request by CJentzsch**
* set target BlockGasLimit to 3141592
* set default GasPrice to 50 shannon (10^9 wei = 10^-9 ether)

### CODE REVIEW

**Comment by CJentzsch** [comment]
(builds only fail due to timeout)

**Comment by gavofyork** [comment]
would be nice to remove all of those default arguments....

**Comment by CJentzsch** [comment]
ok, 2 ways of doing it. 1) specify the default gasPrice globally (similiar to params.cpp) 2) having GasPricer objects everywhere a default gasPrice is needed. so this number only needs to be set at one place.
What do you prefer?

**Comment by chriseth** [comment]
Was unable to review the merge, but the other commits look good.

**Comment by CJentzsch** [comment]
on some builds this test seem to fail:
`/Users/administrator/slave/build-cpp-ethereum-osx-pr/build/test/libp2p/net.cpp:356: fatal error in "deadlineTimer": critical check fired == 1 failed
unknown location:0: fatal error in "deadlineTimer": signal: SIGABRT (application abort requested)
/Users/administrator/slave/build-cpp-ethereum-osx-pr/build/test/libp2p/net.cpp:356: last checkpoint`
But this is absolutely unrelated to this PR.

**Pull request merged**
