### PR TITLE
fixed jsoncpp find_path

### LINKED ISSUE #781: jsoncpp upgrade will need adressing
So, over the weekend there was a new release of [jsoncpp](https://github.com/open-source-parsers/jsoncpp) (0.7.1.). which kind of breaks building things for us. I already got the problem since I am on ArchLinux. They changed the root of the library's include from `jsoncpp/json/json.h` to `json/json.h`.

Since this is the recommended way by the library itself to use includes now we should also comply. A quick patch I tried was to simply add to jsoncpp's cmake find function as suggested by @debris 
```cmake
find_path(
	JSONCPP_INCLUDE_DIR 
	NAMES jsoncpp/json/json.h json/json.h
	DOC "jsoncpp include dir"
)
```

and then change the 3 places where jsoncpp was included in the code, to comply with both the new root directory and the old.
```
libsolidity/InterfaceHandler.h:31:24:#include <jsoncpp/json/json.h>
test/SolidityABIJSON.cpp:25:24:#include <jsoncpp/json/json.h>
test/SolidityNatspecJSON.cpp:24:24:#include <jsoncpp/json/json.h>
```

The problem with this is that `jsonrpccpp` also includes `jsoncpp` and at least the version we are using is trying to include the old root directory.
```
In file included from /usr/local/include/jsonrpccpp/server/abstractserver.h:16:0,
                 from /usr/local/include/jsonrpccpp/server.h:13,
                 from /home/lefteris/ew/cpp-ethereum/libqethereum/QEthereum.h:28,
                 from /home/lefteris/ew/cpp-ethereum/libqethereum/QEthereum.cpp:25:
/usr/local/include/jsonrpccpp/common/procedure.h:16:31: fatal error: jsoncpp/json/json.h: No such file or directory
 #include <jsoncpp/json/json.h>
                               ^
compilation terminated.
libqethereum/CMakeFiles/qethereum.dir/build.make:54: recipe for target 'libqethereum/CMakeFiles/qethereum.dir/QEthereum.cpp.o' failed
make[2]: *** [libqethereum/CMakeFiles/qethereum.dir/QEthereum.cpp.o] Error 1
CMakeFiles/Makefile2:1501: recipe for target 'libqethereum/CMakeFiles/qethereum.dir/all' failed
make[1]: *** [libqethereum/CMakeFiles/qethereum.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Whenever in any OS the new jsoncpp library is used there will be problems. We should address that somehow.

A recommendation would be to do the suggested change above and also
1) Either use a patched version of jsonrpcpp
2) Wait for the maintainer to change it to use the new jsoncpp root

### PR DESCRIPTION
**Pull request by debris**
this with [jsonrpccpp 4.2](https://github.com/ethereum/cpp-ethereum/pull/970) will fix #781

### CODE REVIEW

**Comment by LefterisJP** [comment]
Let's see if the buildbots agree with it and then ... let's merge this. I and all other people using Arch or Mac need this fix.

**Comment by gavofyork** [comment]
doesn't seem to be compiling - do buildbots not need updating to jsonrpccpp 4.2 first?

**Comment by debris** [comment]
@gavofyork no, it should be working fine... i will try to find out, why it's broken on buildbot

**Comment by debris** [comment]
it should be fine now, let's wait for buildbot and merge then

**Pull request merged**
