### PR TITLE
topic bloom filter

### PR DESCRIPTION
**Pull request by gluk256**
TopicBloomFilter is made a template

### CODE REVIEW

**Comment by gluk256** [comment]
I have conducted several tests with different sizes and even with custom bloom() function, and came to conclusion that we need TopicBloomFilter to have the length of 8 bytes. The previous length (4 bytes) was not enough, because if you add 20 samples, then false positive rate exceeds 60%. Besides, it is not stable: it strongly depends on the initial pseudorandom seed, varying between 60% and 75%. If we encrease the length to 8 bytes, then false positive rate will be approximately 20% - 23%, and it does not depend on the pseudorandom seed anymore. 

You can run your own "falsePositiveRate" test. You just need to uncomment the line number 100 in bloomFilter.cpp, and change TopicBloomFilterTest type if necessary.

**Comment by gluk256** [comment]
never mind the errors -- they are not mine

**Comment by gluk256** [comment]
So, this is the relationship between the bloom size and false positive rate if 20 samples are added to the bloom:
4 bytes - 65%
8 bytes - 22%
16 bytes - 6%

**Comment by subtly** [comment]
Need tests to go through :/

**Pull request merged**
