### PR TITLE
Timestamp as int64_t

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by chfast** [comment]
@winsvega Can you change the timestamps in difficulty tests to something _before_ the Sun dies.

**Comment by pirapira** [comment]
All this seems to come from the yellow paper (37) `Hₛ ∈ P₂₅₆`.  The time stamp is supposed to be a 256-bit number.

**Comment by chfast** [comment]
I guess the values in tests are up to 64-bits long. I need 63-bit, because we are using `int64_t`.

**Comment by chfast** [comment]
But a YP change would be nice to have.

**Comment by pirapira** [comment]
I didn't know we are currently testing at most 64-bit.  Then doing it 63-bit is also fine.

**Comment by chfast** [comment]
All timestamps in JSON files are 8 bytes long. @winsvega said they are random.

**Comment by pirapira** [comment]
The test generation procedure has to be documented https://github.com/ethereum/tests/issues/404 .

**Comment by winsvega** [comment]
it is 
`u256 pStamp = test::RandomCode::get().randomUniInt();`

**Comment by chfast** [comment]
How to regenerate them?

**Comment by chfast** [comment]
The `randomUniInt()` returns UINT64_MAX max. Funny :)

**Comment by winsvega** [comment]
if you change the funtion then it is not randomUniInt anymore. (unsigned)

**Comment by chfast** [comment]
Values from 0 to 9223372036854775807. Looks unsigned to me.

**Comment by winsvega** [comment]
int64_t and uint64_t  have the same max() ?

**Comment by chfast** [comment]
No.

**Comment by chfast** [comment]
Now, by default, you get a random int from uniform distribution between 0 and 9223372036854775807. Before it was between 0 and 18446744073709551615. If you want different max value, you can pass is as an argument.

I want int64 max to be default "big" value, not uint64 as before. Because we don't want to relay on any Ethereum client to have unsigned types.

**Comment by winsvega** [comment]
this change will also affect random code generation. but it should be fine

**Comment by chfast** [comment]
Review now?

**Comment by axic** [comment]
@chfast should the evm-c interface be updated (`EnvInfo`) and the static assert be removed?

**Comment by chfast** [comment]
You are right @axic, I missed this one. Will remove it in the next change.

**Pull request merged**
