### PR TITLE
Work around Visual Studio's C2797.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by chriseth** [comment]
Was not able to test that it really fixes the problem. Let us wait for the build results.

**Comment by debris** [comment]
should be fixing, i will check

**Comment by debris** [comment]
it's working

**Comment by LefterisJP** [comment]
Hm .. the Linux build in the buildbot seems to fail with a very funny error.

```
[ 85%] Building CXX object test/CMakeFiles/testeth.dir/SolidityNameAndTypeResolution.cpp.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[2]: *** [alethzero/CMakeFiles/alethzero.dir/MainWin.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
```

**Comment by debris** [comment]
looks like out of memory issue :)

**Comment by chriseth** [comment]
Merging this fix after with "looksgood"s.

**Pull request merged**
