### PR TITLE
Uncomment a unit test file whose tests are completely coommented out

### PR DESCRIPTION
**Pull request by pirapira**

### CODE REVIEW

**Comment by winsvega** [comment]
those tests are commented out because it was failing on travis. or sometimes failing. 
the goal of this tests is to cover code lines with those exceptions being thrown out of blockchain

**Comment by winsvega** [comment]
so maybe we could re enable it and see how it is working at the moment. cause its been a year since this test commented

**Comment by pirapira** [comment]
@winsvega I'll try enabling it.

**Comment by gumb0** [comment]
@winsvega In general, this should be done not by commenting out the test, but by disabling using boost.test methods (probably something like `BOOST_AUTO_TEST_SUITE(BlockQueueSuite, *unit_test::disabled())`
Otherwise test code easily becomes uncompilable and useless.

**Comment by pirapira** [comment]
I uncommented the test and it compiles and works.

**Pull request merged**
