### PR TITLE
script with tests for eth node to node interaction via ethereum console

### PR DESCRIPTION
**Pull request by winsvega**
usage: 
>chmod +x ./nodescript.sh
./nodescript.sh path/to/eth

there is a debug option:
>./nodescript.sh path/to/eth debug

expected result:
>TEST_generateAccount OK
TEST_addPeer OK
TEST_mineBlocks OK
TEST_mineBlocks2 OK
TEST_sendTransaction OK
TEST_mineBlocks3 FAILED
TEST_sendTransaction2 FAILED

### CODE REVIEW

**Comment by yann300** [comment]
After call with Dimitry, in order to run everything in the js we'll need:

- [ ] Function that run a node from JS
- [x] Function that generate/write/replace to a file --> https://nodejs.org/api/fs.html

**Comment by yann300** [comment]
to run a node:
https://gist.github.com/yann300/6e3fdc06b17824ef5098742c9fedd499

**Comment by winsvega** [comment]
Script migrated to https://github.com/ethereum/tests/tree/RPCTests/RPCTests

**Comment by chriseth** [comment]
Can this be closed? The scripts seems to have been moved to a different repository.

**Pull request closed without merging**
