### PR TITLE
Clear storage when overwriting a contract

### LINKED ISSUE #4237: Contract creation at an existing address should clear the storage
The Yellow Paper specifies that the contract creation should clear the storage, but `cpp-ethereum` seems to preserve the storage entries.

This is one reason of https://github.com/ethereum/go-ethereum/issues/14756

### PR DESCRIPTION
**Pull request by pirapira**
Fixes #4237

### CODE REVIEW

**Comment by pirapira** [comment]
I need to fill some blockchain tests.

**Comment by pirapira** [comment]
Now this seems ready to me.

**Comment by gumb0** [comment]
Hm, this way we don't remove the storage trie from the state DB, but just replace the storage root in the account with empty trie root. And we have an orphaned trie in the DB. (This happens in `commit` in State.h)

Not sure how big of a problem this is, it's after all only handling unrealistic scenario of address collision, as I understand...

To fix we'd probably could add a flag to the Account to show that storage was removed.

**Comment by pirapira** [comment]
This kind of change might be reverted during a transaction.  So we need to "garbage-collect" at the end of a transaction.  Let me read around `State.h`.

**Comment by gumb0** [comment]
All the changes are only in `State`'s hashes until transaction end. Then `commit` makes real changes to the state.

Yeah, with CREATE2 it's not only about address collision anymore, so I think we should fix it.

**Comment by gumb0** [comment]
On the other hand I'm not sure whether we ever really delete the storage values from the database...

**Comment by pirapira** [comment]
Hm.  When the chain-reorg happens, old tries come in useful.

**Comment by gumb0** [comment]
The problem might still be there I think, but it's only wasting some disk space in the rare unrealistic case of a contract writing to storage, then address collision in the same block, so it's fine not to complicate the code with optimizing it.

Looks like we don't do this anyway in the case of contract writing to storage and then suiciding in another transaction of the same block.

**Comment by pirapira** [comment]
I created an issue about that https://github.com/ethereum/cpp-ethereum/issues/4264

**Pull request merged**
