### PR TITLE
EIP 684: contract creation on nonempty code or nonzero nonce fails.

### PR DESCRIPTION
**Pull request by pirapira**
Note this change is applied for all blocks from block number zero.

### CODE REVIEW

**Comment by winsvega** [comment]
So once and for all. address collision result in OOG, on all forks including future updates. 

For transactions that will run parallel FCFS rules are applied

**Comment by pirapira** [comment]
FCFS?

**Comment by pirapira** [comment]
I see.  Well, transactions have nonces.

**Comment by winsvega** [comment]
there was an EIP about different transaction proccessing

**Comment by pirapira** [comment]
Rebased.

**Comment by cdetrio** [comment]
EIP 684: https://github.com/ethereum/EIPs/issues/684

**Pull request merged**
