### PR TITLE
Testeth errors out on unknown options

### LINKED ISSUE #4091: testeth should raise an error when an unrecognized option is provided
When `testeth` sees an unknown option after the `--` separation, `testeth` ignores the option.

```
test/testeth -- -hohoho
```

is treated the same as

```
test/testeth
```

However, `testeth` should raise an error in such cases.

### PR DESCRIPTION
**Pull request by pirapira**
This PR makes `testeth` throw an error when it sees an unknown option.  Before the PR, `testeth` silently ignores unknown options.

Fixes #4091 .

### CODE REVIEW

**Comment by pirapira** [comment]
@winsvega I added an issue, and will work on that next week https://github.com/ethereum/cpp-ethereum/issues/4156

**Comment by winsvega** [comment]
--verbosity is not working

**Comment by pirapira** [comment]
I fixed --verbosity.

**Comment by winsvega** [comment]
we could add a check that 

-t  <option>     follows strictly before the --  cause it is a boost option.

**Comment by pirapira** [comment]
I created an issue for that https://github.com/ethereum/cpp-ethereum/issues/4163.  I'll start when this PR is merged.

**Pull request merged**
