### PR TITLE
Updates for Building all cpp-ethereum on MinGW(64)

### PR DESCRIPTION
**Pull request by onepremise**
Not quite sure why the old pull request, #816, closed with my last rebase/push. I had to create a new pull request. All my changes are still there. Odd. I apologize for the inconvenience.

### CODE REVIEW

**Comment by onepremise** [comment]
Figured it out, apparently it's easy to push the original fork in smartGit if you don't explicitly highlight your local branch. Shouldn't happen again.

**Comment by onepremise** [comment]
@gavofyork please review, when you get a chance.

**Comment by debris** [comment]
can we have a buildbot for MinGW? So we don't break anything accidentally.

**Comment by LefterisJP** [comment]
I agree. @caktux may be able to help with setting up a buildbot for a MinGW build.
Thanks for your work @onepremise!

**Comment by onepremise** [comment]
@debris, @LefterisJP, glad I could help contribute! @caktux, I'm available to help setup a buildbot. Just point me in the right direction. Some documentation would be nice if any. I couldn't find any on the wiki, first glance. One thing to note, I'm currently working on my off hours. So I may not respond immediately to everything, but  I will definitely by the end of the day. @caktux, just let me know what I can do to help. Thanks :)

**Comment by caktux** [comment]
Hey, I'll be happy to help set up a builder for this, but as with anything Windows I'll have to leave most of the legwork to you. Anything else I can do to support you I'll be there. Feel free to get in touch on IRC preferably, or Skype. I just added all the documentation needed to get up and running on the [ethereum-buildbot](https://github.com/ethereum/ethereum-buildbot) readme.

**Comment by subtly** [comment]
Still a little concerned here...
@onepremise Why is asio header required in all of those files? (What includes windows.h which asio needs to preempt?) Why does libethereum need to link ssp shlwapi?

**Pull request merged**
