### PR TITLE
libethcore: SealEngine chooses the schedule based on the parameters set in the RPC

### PR DESCRIPTION
**Pull request by pirapira**
This is needed to test https://github.com/ethereum/solidity/pull/1577

### CODE REVIEW

**Comment by pirapira** [comment]
@chriseth   Now I have duplicate `Ethash::evmSchedule()` and `SealEngine::evmSchedule()`.  Which one shall I keep?  I still don't have the big picture.

**Comment by chriseth** [comment]
I guess the cleanest solution would be to implement the function in `SealEngineBase` and remove all other implementations (including the one in SealEngineFace).

**Comment by pirapira** [comment]
@chriseth that doesn't work.  `Ethash` inherits `SealEngineFace` directly.

**Comment by chriseth** [comment]
Does it make sense to inherit from SealEngineBase instead? :)

**Comment by pirapira** [comment]
That does make sense.  I'm treading carefully just because I do not know the current design choices.

**Pull request merged**
