### PR TITLE
Store the response as a string.

### LINKED ISSUE #2610: eth -i often just doesn't work.
https://api.asm.skype.com/s/i?0-weu-d1-40645a79b1338c95f3933bc65a

https://api.asm.skype.com/s/i?0-weu-d2-f011913fa85ed1d5d2ea349275bdcbb5

as reported by stephan

### PR DESCRIPTION
**Pull request by chriseth**
Fixes #2610

### CODE REVIEW

**Comment by debris** [comment]
you can't do that. We build `libjsengine` with [old](https://github.com/ethereum/cpp-ethereum/blob/develop/libjsengine/CMakeLists.txt#L30-L31) `libstdc++` (v8 is using it). It won't work on mac os.

**Comment by debris** [comment]
https://stackoverflow.com/questions/12542971/using-libstdc-compiled-libraries-with-clang-stdlib-libc/12546314#12546314

**Comment by chriseth** [comment]
Updated.

**Comment by LefterisJP** [comment]
looks good to me. @debris what do you think?

**Comment by debris** [comment]
looksgood ;)

**Pull request merged**
