### PR TITLE
WIP - Add support for 'BulkBuild' mode

### PR DESCRIPTION
**Pull request by bobsummerwill**
Now based on 'develop'.
Isn't working, and obviously needs a little love.

### CODE REVIEW

**Comment by arkpar** [comment]
@bobsummerwill consider using https://github.com/sakra/cotire instead. I've used it to enable precompiled headers at some point. It also supports unity builds and can be configured to split the unity file for faster compilation on multicore machines.

**Comment by bobsummerwill** [comment]
Thanks for the tip, @arkpar!

I imagine that I will "finish this PR off" as a first-pass, and then add a new Github issue to try to transition to cotire, which looks like a more comprehensive solution.

**Comment by chfast** [comment]
This *cotire* looks nice :D.

I would also suggest submitting some cleanup changes of the PR in separates PRs.

**Comment by bobsummerwill** [comment]
I agree - looks nice.

What split would you like to see, @chfast?

**Comment by chfast** [comment]
@bobsummerwill Changes like using the namespace `CryptoPP` explicitly.

**Comment by chfast** [comment]
Replaced by #4427.

**Pull request closed without merging**
