### PR TITLE
separate boost random code logic

### PR DESCRIPTION
**Pull request by winsvega**
with this we are ready to implement deterministic random code which will produce a state test from given byte sequence seed

### CODE REVIEW

**Comment by pirapira** [comment]
I scheduled a "rebuild with SSH" to debug the failing test.

**Comment by winsvega** [comment]
which test ?

**Comment by pirapira** [comment]
`ci/circleci: macOS-XCode9`.  When I log in to the instance with SSH, I cannot reproduce the issue.  It's weird.  Maybe we should turn on ASAN for this instance and see what's printed.

**Comment by pirapira** [comment]
I give up debugging this.  I could not reproduce the issue with
* "rebuild with SSH" or
* adding address sanitizer in the cmake options

**Pull request merged**
