### PR TITLE
Fix static initialization fiasco around Invalid256

### PR DESCRIPTION
**Pull request by gumb0**
This came up suddenly - `Invalid256` was a global defined in `livedevcore/Common.cpp` and it was used in initialization of `NullBlockDetails` defined in `BlockDetails.cpp`

### CODE REVIEW

**Comment by gumb0** [comment]
@chfast Yes, I tried, `u256` can't be `constexpr`, `boost::multiprecision` doesn't have `constexpr` constructor (I guess it does heap allocation?)

**Comment by chfast** [comment]
It does not in the "fixed size" form, but maybe it's to complex to be added or they didn't have time to do it yet.

**Comment by chfast** [comment]
Please check out this: http://www.boost.org/doc/libs/1_66_0/libs/multiprecision/doc/html/boost_multiprecision/tut/lits.html.

**Comment by gumb0** [comment]
@chfast ah right, I remember now, constructor is `constexpr`, but the problem is that it's defined as
```
u256 const Invalid256 = ~(u256)0;
```
And `operator~` is definitely not `constexpr`
>However, you will not be able to perform compile-time arithmetic on such types.

**Comment by gumb0** [comment]
`std::numeric_limits<u256>::max()`,  `std::numeric_limits<u256>::infinity()` are also not `constexpr`

**Comment by chfast** [comment]
Try `constexpr static uint256 Invalid256{"0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"};`

**Comment by gumb0** [comment]
^ This doesn't work, I guess constructor from string is not `constexpr`.
But this works, at least on windows:
```
    using namespace boost::multiprecision::literals;
    constexpr u256 Invalid256 = 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff_cppui256;
```

I'll make another PR then.

**Comment by chfast** [comment]
I wanted to suggest literal, but though it will fallback to the constructor anyway. A bit weird :)

**Comment by gumb0** [comment]
I see some metaprogramming magic there in the implemenation of literals, parsing the string through C++ templates etc. https://github.com/boostorg/multiprecision/blob/develop/include/boost/multiprecision/cpp_int/literals.hpp
So it's not a regular constructor magically working at compile time

**Pull request closed without merging**
