### PR TITLE
Crypto++: check if the correct header is included

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by chriseth** [comment]
I'm not sure I see the relation between the change and the title of this PR...

**Comment by chfast** [comment]
On MacOS the include path `/usr/local/include` is very fist one and cause cryptopp headers being included from there, but the library is taken from our local `deps` dir.

This version of the PR tries to show the bug on Travis. Later I will try to fix it.

**Comment by chriseth** [comment]
So do you want this to be merged or are you just experimenting with travis? If you want it to be merged, could you please retrigger the build?

**Comment by chfast** [comment]
@pirapira, can you check this PR **with** cryptopp installed in homebrew? The build should not include headers from homebrew's cryptopp any more. I tested that on Travis OSX, but another confirmation would be great. The checks for CRYPTOPP_VERSION are already in the code.

**Comment by pirapira** [comment]
OK.  I'm on late flights tonight.  I'll try tomorrow.

**Comment by pirapira** [comment]
I'm still seeing a wrong version number
```
$ brew install crypto
<snip>
  Downloading https://github.com/weidai11/cryptopp/archive/CRYPTOPP_5_6_5.tar.gz
<snip>
$ echo $?                                                                                                                                                                          0
$ git checkout wrong-cryptopp
$ git submodule update
$ vim
$ git diff
diff --git a/cmake/EthCompilerSettings.cmake b/cmake/EthCompilerSettings.cmake
index 039240b..0121d4c 100644
--- a/cmake/EthCompilerSettings.cmake
+++ b/cmake/EthCompilerSettings.cmake
@@ -71,7 +71,7 @@ if (("${CMAKE_CXX_COMPILER_ID}" MATCHES "GNU") OR ("${CMAKE_CXX_COMPILER_ID}" MA
        add_compile_options(-fPIC)

        # Configuration-specific compiler settings.
-       set(CMAKE_CXX_FLAGS_DEBUG          "-Og -g -DETH_DEBUG")
+       set(CMAKE_CXX_FLAGS_DEBUG          "-O1 -g -DETH_DEBUG")
        set(CMAKE_CXX_FLAGS_MINSIZEREL     "-Os -DNDEBUG -DETH_RELEASE")
        set(CMAKE_CXX_FLAGS_RELEASE        "-O3 -DNDEBUG -DETH_RELEASE")
        set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -g -DETH_RELEASE")
diff --git a/eth/main.cpp b/eth/main.cpp
index 377654a..2c73171 100644
--- a/eth/main.cpp
+++ b/eth/main.cpp
@@ -66,6 +66,7 @@

#include <ethminer/MinerAux.h>
#include "AccountManager.h"
+#include <cryptopp/config.h>

using namespace std;
using namespace dev;
@@ -305,6 +306,7 @@ bool ExitHandler::s_shouldExit = false;

int main(int argc, char** argv)
{
+        cout << "cryptopp: " << CRYPTOPP_VERSION << endl << flush;
        setDefaultOrCLocale();

        // Init defaults

$ mkdir build
$ cmake -DCMAKE_BUILD_TYPE=Debug ..
$ make
$ eth/eth
cryptopp: 565
```

**Comment by pirapira** [comment]
`make VERBOSE=1` has this line:

```
cd /Users/yh/shared/cpp-ethereum/build/eth && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -DDISABLE_BROKEN_UNIT_TESTS_UNTIL_WE_FIX_THEM -DETH_FATDB -DETH_HAVE_SECP256K1 -DETH_MINIUPNPC -DETH_TRUE -DSHAREDLIB -I/Users/yh/shared/cpp-ethereum/build -I/Users/yh/shared/cpp-ethereum/build/include -I/Users/yh/shared/cpp-ethereum/eth/.. -isystem /usr/local/include -isystem /Users/yh/shared/cpp-ethereum/build/deps/cryptopp/include -isystem /Users/yh/shared/cpp-ethereum/build/deps/jsoncpp/include -isystem /Users/yh/shared/cpp-ethereum/build/deps/jsonrpc/include  -std=c++11 -fpermissive -O1 -g -DETH_DEBUG   -Wall -Wextra -Werror -Wno-unknown-pragmas -fPIC -fstack-protector -fstack-protector-strong -Wno-unused-function -Wno-dangling-else -o CMakeFiles/eth.dir/main.cpp.o -c /Users/yh/shared/cpp-ethereum/eth/main.cpp
```

**Comment by chfast** [comment]
Thanks, but please do not modify the code this way, because only libraries devcrypto and devp2p can correctly include cryptopp. The checks are already there: https://github.com/ethereum/cpp-ethereum/blob/develop/libdevcrypto/CryptoPP.cpp#L31

Can you install homebrew cryptopp and just build this branch?

**Comment by pirapira** [comment]
OK.  I'm trying now.

**Comment by pirapira** [comment]
The build passes but I'm seeing

```
$ test/testeth
Running 309 test cases...
Test Case "rndCode":
Test Case "jsToPublic":
unknown location:0: fatal error: in "commonjs/jsToPublic": memory access violation at address: 0x100f7f000: no mapping at fault address
```

I guess I should open a new issue.

**Pull request merged**
