### PR TITLE
Modify libsecp256k1 to return invalid public key for infinity.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by Gustav-Simonsson** [comment]
Would it not be better to upgrade to the latest version of the lib, which has this check + many other (bug) fixes?

**Comment by chriseth** [comment]
We decided that upgrading is currently not feasible, so we added the check now and will update later.

**Comment by Gustav-Simonsson** [comment]
The secp256k1 implementation is consensus critical code. I strongly recommend that the version in cpp (from February 2014) be upgraded instead of applying selected fixes to it.

The library is not recommended for production by the authors, as it does not have a defined stable release. This makes it even more important to use the latest version.

If you still want to use that old version, you should either applying the following (bug) fixes or motivate why they are not potentially a problem for the consensus-critical code path in Ethereum.

https://github.com/bitcoin/secp256k1/commit/09ca4f32e2fb876b42ca59e322b1643d5a644c91
https://github.com/bitcoin/secp256k1/commit/fa492f059db6e118b2c062989be8467a70a63c3e
https://github.com/bitcoin/secp256k1/commit/21f81a846957408d4a2fe30cff32370567887a93
https://github.com/bitcoin/secp256k1/commit/7a8e385d743e4c2655d9cacf440675d0d39575ad
https://github.com/bitcoin/secp256k1/commit/99f0728f236680a63e8ed30ec52dca5bbdfd705d
https://github.com/bitcoin/secp256k1/commit/9048def7c7495d2e458df80bc5d7affae362ba70
https://github.com/bitcoin/secp256k1/commit/ee3eb4be9efe125b210540b0fd0b9628bc1b7737
https://github.com/bitcoin/secp256k1/commit/35399e08c42fbd81af819deac2ead34b0a6ae51c
https://github.com/bitcoin/secp256k1/commit/a0601cd79c8717577f90962dd51832604a5eddd1
https://github.com/bitcoin/secp256k1/commit/eb2c8ffedf5bd12c5d8e9a92521506df3c60238f
https://github.com/bitcoin/secp256k1/commit/5de4c5dffd22aa4510a5c97d0ad4a9c2eed71d85

**Comment by subtly** [comment]
#2561 updates secp256k1

**Comment by gavofyork** [comment]
likely superseded by #2571

**Pull request closed without merging**
