### PR TITLE
add stBugs

### PR DESCRIPTION
**Pull request by winsvega**
for tests discovered by fuzzer and other
tests: https://github.com/ethereum/tests/pull/365

### CODE REVIEW

**Comment by pirapira** [comment]
Somehow CircleCI fails on Linux and Mac.

**Comment by pirapira** [comment]
Restarted the failed builds.

**Comment by winsvega** [comment]
it fails to fetch tests submodule 
Fetched in submodule path 'test/jsontests', but it did not contain dc9e2cbd33a43872097ed9bc97681a944a0cdd0d. Direct fetching of that commit failed.

**Comment by winsvega** [comment]
should we merge this?

**Comment by winsvega** [comment]
it didn't help. how big should be the depth ?

**Comment by chfast** [comment]
You tell me. Why is the top of the jsontests not used?

**Comment by pirapira** [comment]
@chfast the top of the json test cannot be modified until we see tests passing here.

**Comment by pirapira** [comment]
@chfast if you insist using the top of jsontests, we have a deadlock between the tests repo and cpp-ethereum repo.

**Comment by pirapira** [comment]
@chfast because, whenever a PR comes to ethereum/tests, the PR is kept open until CI builds pass on `ethereum/cpp-ethereum`.  And, since the PR is kept open, the changes are not on `ethereum/tests:develop`.

**Comment by chfast** [comment]
`git log FETCH_HEAD..050cd2587eb05cd47fadc7893ea59fe373fda242 --pretty=oneline | wc -l`
says 223.

**Comment by pirapira** [comment]
That's far.

**Comment by winsvega** [comment]
actually such process with PRs was @chfast  idea in the first place. 
circle should fetch jsontests with other branches too

**Comment by chfast** [comment]
Maybe this command is not accurate to compute commits distance, but try 250.

I had to add it, because cloning tests takes minutes.

**Comment by chfast** [comment]
The process is ok, I just don't understand why we are so far from the top suddenly. Especially when this PR does not change the jsontests submodule.

Cloning selected commit is extremely hard or impossible, because `git clone` downloads the main branch by default. If you find a way we can implement it in Circle CI.

**Comment by chfast** [comment]
Ok, the problem is different. Let me thing a moment about it.

**Comment by chfast** [comment]
Fixed. Let's keep it simple.

**Pull request merged**
