### PR TITLE
fix --filltests

### PR DESCRIPTION
**Pull request by winsvega**

### CODE REVIEW

**Comment by pirapira** [comment]
What kind of problem does it fix?

**Comment by pirapira** [comment]
Are test failures in CircleCI intended?

**Comment by winsvega** [comment]
failures are happening because we have to refill the tests. its in progress. 

it fixes expect section fields check for the blockchain test filler (your comment on a previous PR)

**Comment by pirapira** [comment]
@winsvega so, you are saying the tests should fail on `cpp-ethereum:develop` as well?

**Comment by pirapira** [comment]
@winsvega why is the disabling part of a fix PR?

**Comment by winsvega** [comment]
as I mentioned in skype. we have broken the tests with last commit to the test repo. 
if there was PR with that commit to the cpp develop it wont work

**Comment by pirapira** [comment]
@winsvega https://circleci.com/gh/ethereum/workflows/cpp-ethereum/tree/develop the test is working until we update it.

**Comment by pirapira** [comment]
@winsvega so, this PR breaks CircleCI tests, I think.

**Comment by winsvega** [comment]
not the PR. the tests are not fixed yet

**Comment by pirapira** [comment]
@winsvega CircleCI is not seeing the broken tests yet.  It's seeing some old revision of `ethereum/tests` when everything was fine.  That's why the CircleCI test passes on `develop`.

**Comment by winsvega** [comment]
wait the PR has actually an issue. bc test filler expect section network field could be both string and array...

**Comment by winsvega** [comment]
there are already tests for array. but no tests for string. string are generated with --fillchain option. technically we could generate array. but that would easier to be done when updating all the tests. cause now we have lots of tests with both array and string type.

**Comment by pirapira** [comment]
So, Travis should fill blockchain tests with network section as array and as string type.

**Pull request merged**
