### PR TITLE
Potential fix for EthashAux race condition

### PR DESCRIPTION
**Pull request by LefterisJP**
Some EthashAux functions are protected by mutexes. These mutexes are
normal members of the EthashAux class which itself is a singleton. It
can happen that multiple threads will get inside the singleton creation
`get()` functions when requesting a lock, but the lock will not be
acquired due to the singleton not yet existing.

This leads to multiple threads going in the same code and causing double
free corruption.

Making the mutexes static members of the singleton should hopefully
address the issue

### CODE REVIEW

**Comment by LefterisJP** [comment]
And this is how the problem manifests (and how I detected it):

```
⧎ ◌  12:40:41|p2p|a979fb57…|Geth/v0.9.31-ae36beb3/linux/go1.4.2  Blocks ( 128 entries) 
Press Enter=================================================================
==18767==ERROR: AddressSanitizer: attempting double-free on 0x61700003f080 in thread T2 (verifier1):
    #0 0x588c32 in operator delete(void*) (/home/lefteris/ew/cpp-ethereum/build/eth/eth+0x588c32)
  ◇  12:40:41|verifier0  Searching for seedHash of epoch 22
Press Enter  ◇  12:40:41|verifier2  Searching for seedHash of epoch 22
  ◇  12:40:41|verifier2  Epoch 0 is #00000000…  ◇  12:40:41|verifier0  Epoch 0 is #00000000…
Press Enter
  ◇  12:40:41|verifier2  Epoch 1 is #290decd9…
  ◇  12:40:41|verifier0  Epoch 1 is #290decd9…
  ◇  12:40:41|verifier2  Epoch 2 is #510e4e77…
  ◇  12:40:41|verifier0  Epoch 2 is #510e4e77…
  ◇  12:40:41|verifier2  Epoch 3 is #356e5a2c…
  ◇  12:40:41|verifier0  Epoch 3 is #356e5a2c…
  ◇  12:40:41|verifier2  Epoch 4 is #b903bd76…
  ◇  12:40:41|verifier0  Epoch 4 is #b903bd76…
  ◇  12:40:41|verifier2  Epoch 5 is #f2e59013…
  ◇  12:40:41|verifier0  Epoch 5 is #f2e59013…
  ◇  12:40:41|verifier2  Epoch 6 is #582b0644…
  ◇  12:40:41|verifier0  Epoch 6 is #582b0644…
  ◇  12:40:41|verifier2  Epoch 7 is #6d29f6dd…
  ◇  12:40:41|verifier0  Epoch 7 is #6d29f6dd…
  ◇  12:40:41|verifier2  Epoch 8 is #c307e562…
  ◇  12:40:41|verifier0  Epoch 8 is #c307e562…
  ◇  12:40:41|verifier2  Epoch 9 is #ec9d541d…
  ◇  12:40:41|verifier0  Epoch 9 is #ec9d541d…
  ◇  12:40:41|verifier2  Epoch 10 is #9b2baad7…
  ◇  12:40:41|verifier0  Epoch 10 is #9b2baad7…
  ◇  12:40:41|verifier2  Epoch 11 is #d705bfce…
  ◇  12:40:41|verifier0  Epoch 11 is #d705bfce…
  ◇  12:40:41|verifier2  Epoch 12 is #4db8c3d8…
  ◇  12:40:41|verifier0  Epoch 12 is #4db8c3d8…
  ◇  12:40:41|verifier2  Epoch 13 is #9b1ca7a8…
  ◇  12:40:41|verifier0  Epoch 13 is #9b1ca7a8…
  ◇  12:40:41|verifier2  Epoch 14 is #526ee6e6…
  ◇  12:40:41|verifier0  Epoch 14 is #526ee6e6…
  ◇  12:40:41|verifier2  Epoch 15 is #3db89d40…
  ◇  12:40:41|verifier0  Epoch 15 is #3db89d40…
  ◇  12:40:41|verifier2  Epoch 16 is #f1af2c86…
  ◇  12:40:41|verifier0  Epoch 16 is #f1af2c86…
  ◇  12:40:41|verifier2  Epoch 17 is #1c43434a…
  ◇  12:40:41|verifier0  Epoch 17 is #1c43434a…
  ◇  12:40:41|verifier2  Epoch 18 is #aec7cfe5…
  ◇  12:40:41|verifier0  Epoch 18 is #aec7cfe5…
  ◇  12:40:41|verifier2  Epoch 19 is #c6320e3c…
  ◇  12:40:41|verifier0  Epoch 19 is #c6320e3c…
  ◇  12:40:41|verifier2  Epoch 20 is #4a5c69f2…
  ◇  12:40:41|verifier0  Epoch 20 is #4a5c69f2…
  ◇  12:40:41|verifier2  Epoch 21 is #cdf42a47…
  ◇  12:40:41|verifier0  Epoch 21 is #cdf42a47…
  ◇  12:40:41|verifier2  Epoch 22 is #77e29faa…
  ◇  12:40:41|verifier0  Epoch 22 is #77e29faa…
  ◇  12:40:41|verifier3  Searching for seedHash of epoch 22
  ◇  12:40:41|verifier3  Epoch 0 is #00000000…
  ◇  12:40:41|verifier3  Epoch 1 is #290decd9…
  ◇  12:40:41|verifier3  Epoch 2 is #510e4e77…
  ◇  12:40:41|verifier3  Epoch 3 is #356e5a2c…
  ◇  12:40:41|verifier3  Epoch 4 is #b903bd76…
  ◇  12:40:41|verifier3  Epoch 5 is #f2e59013…
  ◇  12:40:41|verifier3  Epoch 6 is #582b0644…
  ◇  12:40:41|verifier3  Epoch 7 is #6d29f6dd…
  ◇  12:40:41|verifier3  Epoch 8 is #c307e562…
  ◇  12:40:41|verifier3  Epoch 9 is #ec9d541d…
  ◇  12:40:41|verifier3  Epoch 10 is #9b2baad7…
  ◇  12:40:41|verifier3  Epoch 11 is #d705bfce…
  ◇  12:40:41|verifier3  Epoch 12 is #4db8c3d8…
  ◇  12:40:41|verifier3  Epoch 13 is #9b1ca7a8…
  ◇  12:40:41|verifier3  Epoch 14 is #526ee6e6…
  ◇  12:40:41|verifier3  Epoch 15 is #3db89d40…
  ◇  12:40:41|verifier3  Epoch 16 is #f1af2c86…
  ◇  12:40:41|verifier3  Epoch 17 is #1c43434a…
  ◇  12:40:41|verifier3  Epoch 18 is #aec7cfe5…
  ◇  12:40:41|verifier3  Epoch 19 is #c6320e3c…
  ◇  12:40:41|verifier3  Epoch 20 is #4a5c69f2…
  ◇  12:40:41|verifier3  Epoch 21 is #cdf42a47…
  ◇  12:40:41|verifier3  Epoch 22 is #77e29faa…
Press Enter    #1 0x7f070e26ee9a in std::vector<dev::FixedHash<32u>, std::allocator<dev::FixedHash<32u> > >::_M_default_append(unsigned long) /usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/5.1.0/../../../../include/c++/5.1.0/bits/vector.tcc:578:8
    #2 0x7f070d485812 in dev::eth::EthashAux::seedHash(unsigned int) /home/lefteris/ew/cpp-ethereum/libethcore/EthashAux.cpp:75:3
    #3 0x7f070d4aeaa8 in dev::eth::BlockInfo::seedHash() const /home/lefteris/ew/cpp-ethereum/libethcore/BlockInfo.cpp:68:16
    #4 0x7f070d489184 in dev::eth::EthashAux::eval(dev::eth::BlockInfo const&, dev::FixedHash<8u> const&) /home/lefteris/ew/cpp-ethereum/libethcore/EthashAux.cpp:246:14
    #5 0x7f070d46d32f in dev::eth::EthashAux::eval(dev::eth::BlockInfo const&) /home/lefteris/ew/cpp-ethereum/libethcore/EthashAux.h:81:64
    #6 0x7f070d4689ca in dev::eth::Ethash::verify(dev::eth::BlockInfo const&) /home/lefteris/ew/cpp-ethereum/libethcore/Ethash.cpp:117:16
    #7 0x7f070d4b0630 in dev::eth::BlockInfo::populateFromHeader(dev::RLP const&, dev::eth::Strictness, dev::FixedHash<32u> const&) /home/lefteris/ew/cpp-ethereum/libethcore/BlockInfo.cpp:152:46
    #8 0x7f070d4ad014 in dev::eth::BlockInfo::populate(dev::vector_ref<unsigned char const>, dev::eth::Strictness, dev::FixedHash<32u> const&) /home/lefteris/ew/cpp-ethereum/libethcore/BlockInfo.cpp:200:2
    #9 0x7f070e25d3f4 in dev::eth::BlockInfo::populate(std::vector<unsigned char, std::allocator<unsigned char> > const&, dev::eth::Strictness, dev::FixedHash<32u> const&) /home/lefteris/ew/cpp-ethereum/libethereum/../libethcore/BlockInfo.h:126:93
    #10 0x7f070e23902b in dev::eth::BlockChain::verifyBlock(std::vector<unsigned char, std::allocator<unsigned char> > const&, std::function<void (dev::Exception&)> const&, unsigned int) /home/lefteris/ew/cpp-ethereum/libethereum/BlockChain.cpp:1078:3
    #11 0x7f070e3f02dd in dev::eth::BlockQueue::verifierBody() /home/lefteris/ew/cpp-ethereum/libethereum/BlockQueue.cpp:112:19
    #12 0x7f070e3ff284 in dev::eth::BlockQueue::BlockQueue()::$_0::operator()() const /home/lefteris/ew/cpp-ethereum/libethereum/BlockQueue.cpp:57:4
    #13 0x7f07099d32ef in execute_native_thread_routine /build/gcc-multilib/src/gcc-5-20150519/libstdc++-v3/src/c++11/thread.cc:84
    #14 0x7f0709ca3353 in start_thread (/usr/lib/libpthread.so.0+0x7353)
    #15 0x7f0708d38bfc in __clone (/usr/lib/libc.so.6+0xe7bfc)

0x61700003f080 is located 0 bytes inside of 736-byte region [0x61700003f080,0x61700003f360)
freed by thread T4 (verifier3) here:
    #0 0x588c32 in operator delete(void*) (/home/lefteris/ew/cpp-ethereum/build/eth/eth+0x588c32)
    #1 0x7f070e26ee9a in std::vector<dev::FixedHash<32u>, std::allocator<dev::FixedHash<32u> > >::_M_default_append(unsigned long) /usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/5.1.0/../../../../include/c++/5.1.0/bits/vector.tcc:578:8
    #2 0x7f070d485812 in dev::eth::EthashAux::seedHash(unsigned int) /home/lefteris/ew/cpp-ethereum/libethcore/EthashAux.cpp:75:3
    #3 0x7f070d4aeaa8 in dev::eth::BlockInfo::seedHash() const /home/lefteris/ew/cpp-ethereum/libethcore/BlockInfo.cpp:68:16
    #4 0x7f070d489184 in dev::eth::EthashAux::eval(dev::eth::BlockInfo const&, dev::FixedHash<8u> const&) /home/lefteris/ew/cpp-ethereum/libethcore/EthashAux.cpp:246:14
    #5 0x7f070d46d32f in dev::eth::EthashAux::eval(dev::eth::BlockInfo const&) /home/lefteris/ew/cpp-ethereum/libethcore/EthashAux.h:81:64
    #6 0x7f070d4689ca in dev::eth::Ethash::verify(dev::eth::BlockInfo const&) /home/lefteris/ew/cpp-ethereum/libethcore/Ethash.cpp:117:16
    #7 0x7f070d4b0630 in dev::eth::BlockInfo::populateFromHeader(dev::RLP const&, dev::eth::Strictness, dev::FixedHash<32u> const&) /home/lefteris/ew/cpp-ethereum/libethcore/BlockInfo.cpp:152:46
    #8 0x7f070d4ad014 in dev::eth::BlockInfo::populate(dev::vector_ref<unsigned char const>, dev::eth::Strictness, dev::FixedHash<32u> const&) /home/lefteris/ew/cpp-ethereum/libethcore/BlockInfo.cpp:200:2
    #9 0x7f070e25d3f4 in dev::eth::BlockInfo::populate(std::vector<unsigned char, std::allocator<unsigned char> > const&, dev::eth::Strictness, dev::FixedHash<32u> const&) /home/lefteris/ew/cpp-ethereum/libethereum/../libethcore/BlockInfo.h:126:93
    #10 0x7f070e23902b in dev::eth::BlockChain::verifyBlock(std::vector<unsigned char, std::allocator<unsigned char> > const&, std::function<void (dev::Exception&)> const&, unsigned int) /home/lefteris/ew/cpp-ethereum/libethereum/BlockChain.cpp:1078:3
    #11 0x7f070e3f02dd in dev::eth::BlockQueue::verifierBody() /home/lefteris/ew/cpp-ethereum/libethereum/BlockQueue.cpp:112:19
    #12 0x7f070e3ff284 in dev::eth::BlockQueue::BlockQueue()::$_0::operator()() const /home/lefteris/ew/cpp-ethereum/libethereum/BlockQueue.cpp:57:4
    #13 0x7f07099d32ef in execute_native_thread_routine /build/gcc-multilib/src/gcc-5-20150519/libstdc++-v3/src/c++11/thread.cc:84

previously allocated by thread T1 (verifier0) here:
    #0 0x588672 in operator new(unsigned long) (/home/lefteris/ew/cpp-ethereum/build/eth/eth+0x588672)
    #1 0x7f070e26ee48 in std::vector<dev::FixedHash<32u>, std::allocator<dev::FixedHash<32u> > >::_M_default_append(unsigned long) /usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/5.1.0/../../../../include/c++/5.1.0/bits/vector.tcc:557:28
    #2 0x7f070d485812 in dev::eth::EthashAux::seedHash(unsigned int) /home/lefteris/ew/cpp-ethereum/libethcore/EthashAux.cpp:75:3
    #3 0x7f070d4aeaa8 in dev::eth::BlockInfo::seedHash() const /home/lefteris/ew/cpp-ethereum/libethcore/BlockInfo.cpp:68:16
    #4 0x7f070d489184 in dev::eth::EthashAux::eval(dev::eth::BlockInfo const&, dev::FixedHash<8u> const&) /home/lefteris/ew/cpp-ethereum/libethcore/EthashAux.cpp:246:14
    #5 0x7f070d46d32f in dev::eth::EthashAux::eval(dev::eth::BlockInfo const&) /home/lefteris/ew/cpp-ethereum/libethcore/EthashAux.h:81:64
    #6 0x7f070d4689ca in dev::eth::Ethash::verify(dev::eth::BlockInfo const&) /home/lefteris/ew/cpp-ethereum/libethcore/Ethash.cpp:117:16
    #7 0x7f070d4b0630 in dev::eth::BlockInfo::populateFromHeader(dev::RLP const&, dev::eth::Strictness, dev::FixedHash<32u> const&) /home/lefteris/ew/cpp-ethereum/libethcore/BlockInfo.cpp:152:46
    #8 0x7f070d4ad014 in dev::eth::BlockInfo::populate(dev::vector_ref<unsigned char const>, dev::eth::Strictness, dev::FixedHash<32u> const&) /home/lefteris/ew/cpp-ethereum/libethcore/BlockInfo.cpp:200:2
    #9 0x7f070e25d3f4 in dev::eth::BlockInfo::populate(std::vector<unsigned char, std::allocator<unsigned char> > const&, dev::eth::Strictness, dev::FixedHash<32u> const&) /home/lefteris/ew/cpp-ethereum/libethereum/../libethcore/BlockInfo.h:126:93
    #10 0x7f070e23902b in dev::eth::BlockChain::verifyBlock(std::vector<unsigned char, std::allocator<unsigned char> > const&, std::function<void (dev::Exception&)> const&, unsigned int) /home/lefteris/ew/cpp-ethereum/libethereum/BlockChain.cpp:1078:3
    #11 0x7f070e3f02dd in dev::eth::BlockQueue::verifierBody() /home/lefteris/ew/cpp-ethereum/libethereum/BlockQueue.cpp:112:19
    #12 0x7f070e3ff284 in dev::eth::BlockQueue::BlockQueue()::$_0::operator()() const /home/lefteris/ew/cpp-ethereum/libethereum/BlockQueue.cpp:57:4
    #13 0x7f07099d32ef in execute_native_thread_routine /build/gcc-multilib/src/gcc-5-20150519/libstdc++-v3/src/c++11/thread.cc:84

Thread T2 (verifier1) created by T0 here:
    #0 0x5514c0 in __interceptor_pthread_create (/home/lefteris/ew/cpp-ethereum/build/eth/eth+0x5514c0)
    #1 0x7f07099d3446 in __gthread_create /build/gcc-multilib/src/gcc-build/x86_64-unknown-linux-gnu/libstdc++-v3/include/x86_64-unknown-linux-gnu/bits/gthr-default.h:662
    #2 0x7f07099d3446 in std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>, void (*)()) /build/gcc-multilib/src/gcc-5-20150519/libstdc++-v3/src/c++11/thread.cc:148

Thread T4 (verifier3) created by T0 here:
    #0 0x5514c0 in __interceptor_pthread_create (/home/lefteris/ew/cpp-ethereum/build/eth/eth+0x5514c0)
    #1 0x7f07099d3446 in __gthread_create /build/gcc-multilib/src/gcc-build/x86_64-unknown-linux-gnu/libstdc++-v3/include/x86_64-unknown-linux-gnu/bits/gthr-default.h:662
    #2 0x7f07099d3446 in std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>, void (*)()) /build/gcc-multilib/src/gcc-5-20150519/libstdc++-v3/src/c++11/thread.cc:148

Thread T1 (verifier0) created by T0 here:
    #0 0x5514c0 in __interceptor_pthread_create (/home/lefteris/ew/cpp-ethereum/build/eth/eth+0x5514c0)
    #1 0x7f07099d3446 in __gthread_create /build/gcc-multilib/src/gcc-build/x86_64-unknown-linux-gnu/libstdc++-v3/include/x86_64-unknown-linux-gnu/bits/gthr-default.h:662
    #2 0x7f07099d3446 in std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>, void (*)()) /build/gcc-multilib/src/gcc-5-20150519/libstdc++-v3/src/c++11/thread.cc:148

SUMMARY: AddressSanitizer: double-free ??:0 operator delete(void*)
==18767==ABORTING
```

**Comment by gavofyork** [comment]
bad practice to give singletons statics members. better to have a single static member `x_this` which is locked during `get()` to make sure `get()` always returns the singleton object.

**Comment by LefterisJP** [comment]
But that would still give a static member to a singleton :)

I'll add it nonetheless.

**Comment by gavofyork** [comment]
true - it's not ideal; but it cuts it down from 3 infractions to 1. could also make it a static global in the .cpp file.

**Comment by chfast** [comment]
I would implement singletons with [magic statics](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2008/n2660.htm):
```cpp
static EthashAux& get() { static EthashAux instance; return instance; }
```
It is simple and thread-safe (except Visual Studio 2013, but 2015 will catch up). Do you agree?

**Comment by LefterisJP** [comment]
It looks simpler and nicer indeed, I wasn't aware of this C++11 feature.

But we do use Visual Studio 2013 in Windows at the moment, so that would be a problem at least for now.

**Comment by chfast** [comment]
Another feature you might want to use is [std::call_once](http://en.cppreference.com/w/cpp/thread/call_once).

**Comment by gavofyork** [comment]
yeah `call_once` looks reasonably useful here.

**Comment by chfast** [comment]
Looks nice :)

**Pull request merged**
