### PR TITLE
Executive refactor

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by gavofyork** [comment]
why switch shared_ptr to unique_ptr?

**Comment by chfast** [comment]
Because ExtVM instance is never shared. Executive is the only owner.

**Comment by gavofyork** [comment]
sure, and indeed given *that*, they're essentially equivalent here, the only difference being that shared_ptr doesn't require the ExtVM to be fully declared prior to a usage of the safe pointer.

**Comment by chfast** [comment]
Right. Another option is to move Executive destructor to .cpp. Both solutions are a bit misleading for me. shared_ptr suggests something is shared but is not. Destructor in .cpp suggests there is something specific in there, but is not.

Tell me what to do.

**Comment by gavofyork** [comment]
shared_ptr with a short comment about why.

**Comment by chfast** [comment]
Done.

**Pull request merged**
