### PR TITLE
Travis CI: enable tests on MacOS

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by chriseth** [comment]
Can you rebase this, please?

**Comment by chfast** [comment]
Still failing on the same test: AccountDiff. BTW, I killed Windows build, because it is not relevant.

**Comment by chriseth** [comment]
Wasn't accountdiff removed? Or did you not yet create a pull request for that?

**Comment by chfast** [comment]
It is the old comment. @pirapira identified the issue in the std::map move.

**Comment by chfast** [comment]
Do we want to try this?

**Comment by chriseth** [comment]
Last time, it always slowed us down tremendously, but we can try again once more.

**Pull request closed without merging**
