### PR TITLE
Mix: Add memory address in memory dump.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by chriseth** [comment]
Not the best solution, but having addresses is really important.

**Comment by LefterisJP** [comment]
looks good. So this is not used yet, right? I did not see any new calls to `memDumpToList()` using the 3rd argument.

**Comment by LefterisJP** [comment]
looks good. So this is not used yet, right? I did not see any new calls to `memDumpToList()` using the 3rd argument.

**Comment by yann300** [comment]
looks good.

**Pull request merged**
