### PR TITLE
getstuff downloads llvm 3.7svn on windows

### PR DESCRIPTION
**Pull request by debris**

### CODE REVIEW

**Comment by LefterisJP** [comment]
This is for the windowsjit build, yes? Has it been tested?

**Comment by debris** [comment]
I think that @pawel has tested it. He requested me to upload it to the buildbot.

**Comment by LefterisJP** [comment]
yea we need this dependency in Windows. If it's tested and works then it's awesome. Will also test in Windows when I get a Windows machine.

**Comment by chfast** [comment]
I can test it locally if you want. But the only part that can go wrong is downloading and unpacking. The LLVM prebuilt libraries are fine.

**Comment by LefterisJP** [comment]
No it should be fine. This is what I wanted to hear.

**Pull request merged**
