### PR TITLE
Max code size from spurious dragon

### LINKED ISSUE #4228: Max code size activation block is wrong?
@cdetrio reports
> cpp-eth and GeneralStateTests are using EIP170 contract size limit within the EIP150 fork configuration

while EIP 170 was announced part of [Spurious Dragon](https://blog.ethereum.org/2016/11/18/hard-fork-no-4-spurious-dragon/), which does not contain EIP150.

If a change is made in `cpp-ethereum`, the consensus tests need to be updated for EIP150 network configuration.

### PR DESCRIPTION
**Pull request by pirapira**
Fixes #4228

### CODE REVIEW

**Comment by winsvega** [comment]
what is the according PR in tests repo?

**Comment by pirapira** [comment]
I think I forgot to create a PR.

**Comment by pirapira** [comment]
I created one here https://github.com/ethereum/tests/pull/219

**Comment by winsvega** [comment]
need rebase

**Comment by pirapira** [comment]
Rebased.

**Comment by pirapira** [comment]
@winsvega you merged too quick.  For example, I might have made a mistake rebasing the test branch, and Travis could have caught it.

**Comment by winsvega** [comment]
no time to wait for travis

**Pull request merged**
