### PR TITLE
change typedef to using according to preferred coding style

### PR DESCRIPTION
**Pull request by guanqun**
However, all the third party libraries code are not touched.

### CODE REVIEW

**Comment by LefterisJP** [comment]
you probably need a rebase to develop

**Comment by guanqun** [comment]
Hi @LefterisJP, I've rebased it on top of the latest develop branch, please check, thanks!

**Comment by guanqun** [comment]
FYI. The window build error is not caused by this commit.

**Comment by LefterisJP** [comment]
yes I know, it's failing due to unrelated issues. But since these changes are touching code outside of Solidity we need @gavofyork to check the PR and merge it.

**Pull request merged**
