### PR TITLE
WIP - Add initial Alpine Linux support to install_deps.sh

### PR DESCRIPTION
**Pull request by bobsummerwill**
Needs testing, and to add jsonrpccpp.

### CODE REVIEW

**Comment by bobsummerwill** [comment]
Hey @rainbeam, @VoR0220,

Please could one of you try this out on an Alpine Linux setup?

I think we're just missing `json-rpc-cpp` (which will probably need to be a cut-and-paste of the build-from-source for that package which we already have in Debian and Ubuntu), but some verification that the other packages are working would be great.    Thanks!

**Comment by rainbeam** [comment]
`lsb_release` won't work in Alpine. For solidity I created a more generic os detection function: 

https://github.com/ethereum/solidity/blob/develop/scripts/install_deps.sh#L51-L61

**Comment by bobsummerwill** [comment]
You did, and I just forgot to pull that code over here too.   Done now!

Thanks for that :-)

**Comment by rainbeam** [comment]
You forgot to change the lsb_release invocation as well:

https://github.com/ethereum/solidity/blob/develop/scripts/install_deps.sh#L132

Also, change the script to use `sh` rather than `bash`.

Regarding dependencies, Alpine mainline ('stable') doesn't have miniupnpc, leveldb or json-rpc-cpp. When building from the umbrella I had to build these from source:

https://github.com/rainbeam/eth-static/blob/master/Dockerfile

You are also missing `curl-dev` and `libmicrottpd-dev`.

**Comment by bobsummerwill** [comment]
Thanks - fixed some of those.    build-from-source bits still TODO.

curl and libmicrohttpd were not missing - just not using the -dev variants.

**Comment by chfast** [comment]
Done.

**Pull request closed without merging**
