### PR TITLE
Add ETHASHCL=1 to default cmake bundle

### PR DESCRIPTION
**Pull request by LefterisJP**

### CODE REVIEW

**Comment by gavofyork** [comment]
windows fails?
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
C:/Users/Administrator/buildbot/build-cpp-ethereum-win-pr/build/libethash-cl/OpenCL_INCLUDE_DIR
   used as include directory in directory C:/Users/Administrator/buildbot/build-cpp-ethereum-win-pr/build/libethash-cl
OpenCL_LIBRARY (ADVANCED)
    linked by target "ethash-cl" in directory C:/Users/Administrator/buildbot/build-cpp-ethereum-win-pr/build/libethash-cl
OpenCL_LIBRARY_DEBUG
    linked by target "ethash-cl" in directory C:/Users/Administrator/buildbot/build-cpp-ethereum-win-pr/build/libethash-cl
```

**Comment by LefterisJP** [comment]
Yep, I am working on it, this PR's sole purpose is to make the buildbot work with ETHASHCL=1. This is why this is not yet at "Please Review"

**Comment by LefterisJP** [comment]
Rebased on develop

**Comment by gavofyork** [comment]
included in whizz branch.

**Pull request closed without merging**
