### PR TITLE
[rpc] implementation of logsEx proposal

### PR DESCRIPTION
**Pull request by debris**
proposal: https://github.com/ethereum/wiki/wiki/Proposal:-Reversion-Notification

This pr includes #2420 

Changes:

- `eth_newFilterEx`
- `eth_getFilterChangesEx`
- `eth_getFilterLogsEx`
- `eth_getLogsEx`
- support for anonymous (without an address) filter logs 
- support for filter logs without address and topics (only fromBlock, toBlock)
- logs have field `polarity`
- logs are returned in order, from earliest to latest
- cpp-ethereum passes all tests from [this branch](https://github.com/ethereum/rpc-tests/pull/5) or rpc-tests repository
- minor other changes

### CODE REVIEW

**Comment by gavofyork** [comment]
need tests asap.

**Comment by gavofyork** [comment]
also rebase.

**Comment by debris** [comment]
I rebased on latest develop and have few questions regarding tests


- What kind of tests should I write? Should I add them to [rpc-tests](https://github.com/ethereum/rpc-tests) repo? 
- @CJentzsch Is it possible to simulate fork using test `.json` files? If yes, how can I do that?

**Comment by gavofyork** [comment]
rpc-tests, yes.

suggest contacting christoph directly.

**Comment by gavofyork** [comment]
*bump*

**Comment by gavofyork** [comment]
rebase on whizz :)

**Comment by debris** [comment]
I will open new pr.

**Comment by debris** [comment]
reopened in #2504

**Pull request closed without merging**
