### PR TITLE
CMake: static libs and working install

### LINKED ISSUE #3244: CentOS - Let the use of lib64
Hi
I am building the RPM, and I realized that it always try to install in /usr/lib, which it should be /usr/lib64 for 64 bits systems.
Most distributions use this -DLIB_SUFFIX=64 to tell the architecture. Can you add this support into the CMAKE or maybe LIB_INSTALL_DIR, whatever you consider is the best.

### LINKED ISSUE #3516: Fix "make install"
Some people try to build cpp-ethereum from source, but even `make install` does not work.

Proposed changes:
- [ ] Do not install headers. There is a mess there, and I suspect nobody is going to use them anyway.
- [ ] Check if every shared libs are installed.
- [ ] Add integration test for it?
- [ ] Build static libs (without installing them) to limit number of targets being installed?

### PR DESCRIPTION
**Pull request by chfast**
The following changes are included:
1. A cleanup of "static lib" CMake options. Now it is controlled by `-DBUILD_SHARED_LIBS` "standard" flag.
2. `BUILD_SHARED_LIBS` is `Off` by default => static libs are built. 
3. No libs are going to be installed by `make install`, except evmjit shared lib (comes from dependent project).
4. Only 3 binaries are going to be installed: eth, ethminer and ethvm.
5. `ldconfig` probably still needed on Linux if built with EVMJIT. I'm not sure CMake is able to handle that nicely, without hacking RPATHs.

Resolves #3516.
Resolves #3244.

### CODE REVIEW

**Comment by chriseth** [comment]
OMG this is wonderful!

**Comment by chriseth** [comment]
Does this work with ppa-release and docker?

**Comment by pirapira** [comment]
I'm getting some error from the installed `eth` on Mac OS 10.11.6 and XCode 8.2.1.

```
$ git clone git@github.com:ethereum/cpp-ethereum.git cpp-ethereum3518
$ cd cpp-ethereum3518
$ git submodule init
$ git submodule update --recursive
$ mkdir build
$ cd build
$ cmake ..
$ make install
<snip>
-- Installing: /usr/local/bin/eth
<snip>
$ eth
cpp-ethereum, a C++ Ethereum client
  ✘  08:40:57.420|  Account address is either not defined or not in hex format /Users/yh/.web3/keys/08a17fa4-4551-3410-c59d-14de38539979.json
  ✘  08:40:57.421|  Account address is either not defined or not in hex format /Users/yh/.web3/keys/4447760f-c912-bb50-c5b7-5f8181f1c291.json
  ✘  08:40:57.422|  Account address is either not defined or not in hex format /Users/yh/.web3/keys/7fe9ccd5-65b1-12b6-c86f-b0b192acb7f2.json
  ✘  08:40:57.422|  Account address is either not defined or not in hex format /Users/yh/.web3/keys/973cf067-fea6-8f0d-a150-aea355c90ed7.json
  ✘  08:40:57.423|  Account address is either not defined or not in hex format /Users/yh/.web3/keys/f108ac70-ab10-efe5-fa90-7bf6b5a0abf0.json
  ✘  08:40:57.423|  Account address is either not defined or not in hex format /Users/yh/.web3/keys/fce18a33-a180-fd36-1a52-1d15cf2e8847.json
libc++abi.dylib: terminating with uncaught exception of type CryptoPP::UnknownOID: BER decode error: unknown object identifier
[1]    47351 abort      eth
$ which eth
/usr/local/bin/eth
$ eth --version
eth version 1.3.0
eth network protocol version: 63
Client database version: 12041
Build: Darwin/appleclang/Interpreter/RelWithDebInfo
```

**Comment by pirapira** [comment]
I'm getting some segmentation fault on this PR on Mac OS 10.11.6, XCode 8.2.1.

```
$ git clone git@github.com:ethereum/cpp-ethereum.git cpp-ethereum3518
$ cd cpp-ethereum3518
$ git checkout cmake-static-install
$ git submodule init
$ git submodule update --recursive
$ mkdir build
$ cd build
$ cmake ..
$ make install
<snip>
-- Installing: /usr/local/bin/eth
<snip>
$ eth
cpp-ethereum, a C++ Ethereum client
[1]    52085 segmentation fault  eth
$ which eth
/usr/local/bin/eth
$ eth/eth
cpp-ethereum, a C++ Ethereum client
[1]    52132 segmentation fault  eth/eth
```

I'll try on `develop` with `eth/eth` too.

**Comment by pirapira** [comment]
On `develop` I see a different issue and cannot reproduce the segmentation fault.  I ignore the problem on `develop` and try to identify the problem on `cmake-static-install`.

**Comment by pirapira** [comment]
After doing `valgrind -v eth/eth &> valgrind.out`, I see
```
==62383== Process terminating with default action of signal 11 (SIGSEGV)
==62383==  Access not within mapped region at address 0x105007000
==62383==    at 0x1016CFF49: _platform_memmove$VARIANT$Haswell (in /usr/lib/system/libsystem_platform.dylib)
==62383==    by 0x10001E110: _ZNSt3__16vectorIhNS_9allocatorIhEEE18__construct_at_endIPhEENS_9enable_ifIXsr21__is_forward_iteratorIT_EE5valueEvE4typeES7_S7_m (memory:1605)
==62383==    by 0x10025BDDF: CryptoPP::operator+(CryptoPP::OID const&, unsigned long) (asn.h:541)
==62383==    by 0x100323333: CryptoPP::ASN1::iso_us() (in eth/eth)
==62383==    by 0x1003231B9: CryptoPP::ASN1::ansi_x9_62_curves() (in eth/eth)
==62383==    by 0x1003215D9: CryptoPP::ASN1::secp192r1() (in eth/eth)
==62383==    by 0x1002FF8BB: CryptoPP::GetRecommendedParameters(CryptoPP::EcRecommendedParameters<CryptoPP::ECP> const*&, CryptoPP::EcRecommendedParameters<CryptoPP::ECP> const*&) (in eth/eth)
==62383==    by 0x1002FE4A6: CryptoPP::DL_GroupParameters_EC<CryptoPP::ECP>::Initialize(CryptoPP::OID const&) (in eth/eth)
==62383==    by 0x1002FEAD4: CryptoPP::DL_GroupParameters_EC<CryptoPP::ECP>::DL_GroupParameters_EC(CryptoPP::OID const&) (in eth/eth)
==62383==    by 0x10025BBB2: dev::crypto::Secp256k1PP::Secp256k1PP() (CryptoPP.h:157)
==62383==    by 0x100259B3B: dev::crypto::Secp256k1PP::get() (CryptoPP.h:100)
==62383==    by 0x10025B257: dev::KeyPair::populateFromSecret(dev::SecureFixedHash<32u> const&) (Common.cpp:302)
```

**Comment by chfast** [comment]
@pirapira Is this the full call stack? It might be dynamic initialization issue of globals as before...

**Comment by chfast** [comment]
Maybe we should enable testing on MacOS?

**Comment by pirapira** [comment]
@chfast that was everything that `valgrind` printed for me.  Your guess might be right about static initialization.  Just ten lines above, I see something like "locating libraries and allocating memory".
```
--62383-- REDIR: 0x1015ea2d7 (libsystem_malloc.dylib:malloc_zone_register) redirected to 0x101010aef (malloc_zone_register)
--62383-- REDIR: 0x1015f40aa (libsystem_malloc.dylib:malloc_zone_unregister) redirected to 0x101010b05 (malloc_zone_unregister)
--62383-- REDIR: 0x101494012 (libsystem_c.dylib:strrchr) redirected to 0x101010cd8 (strrchr)
--62383-- REDIR: 0x1015ea13a (libsystem_malloc.dylib:malloc_create_zone) redirected to 0x101010a9e (malloc_create_zone)
```

**Comment by pirapira** [comment]
This problem disappeared after `brew uninstall cryptopp`.

**Comment by chfast** [comment]
Yupi!

**Pull request merged**
