### PR TITLE
evm: Fix CREATE2 implementation

### PR DESCRIPTION
**Pull request by chfast**
The memory requirements for CREATE2 were not correctly checked.

### CODE REVIEW

**Comment by chfast** [comment]
No regressions on my machine, but I will wait for all builds...

**Comment by pirapira** [comment]
That means tests are missing.

**Comment by chfast** [comment]
@winsvega said we don't have any tests for Constantinople.

**Comment by winsvega** [comment]
we have some transaction tests.
for constantinople there was zeroSig tests. but its removed from the repo for now.
new tests are not developed. because no specs (EIPs) and roadmap is defined.

**Pull request merged**
