### PR TITLE
purge aux mem too

### PR DESCRIPTION
**Pull request by CJentzsch**

### CODE REVIEW

**Comment by gavofyork** [comment]
does this run all tests and sync the blockchain without issue?

**Comment by CJentzsch** [comment]
All tests pass and blockchain syncs without issues.
But I will make a statePruning branch for the more sensible core changes.

**Comment by gavofyork** [comment]
ok - i'll apply in the 1.1 branch (i.e. develop, after we've released 1.0)

**Comment by CJentzsch** [comment]
added more tests, you may want to review again, although I think its fine.

**Pull request closed without merging**
