### PR TITLE
Remove the blockhash contract when it is empty

### LINKED ISSUE #4457: testeth sometimes produces a poststate containing empty accounts for Constantinople network
For example https://github.com/ethereum/tests/pull/303#discussion_r136947505

### PR DESCRIPTION
**Pull request by pirapira**
During Constantinople Blockchaintests, `constantinopleForkBlock` is set to zero, but the block zero is never processed, so the blockhash contract stays empty.  After that, in block number one, the blockhash contract is called, so it is created in the trie as an empty account.  And the empty blockhash contract stays because the commit behavior was not `RemoveEmptyAccounts`.

This PR changes the commit behavior.  I'm discussing with @winsvega what to do about the blockhash contract deployment.

Fixes #4457.

Work in progress: filling blockchaintests on this PR.

### CODE REVIEW

**Comment by gumb0** [comment]
Yeah, I think if `constantinopleForkBlock  == 0`, blockhash contract should be part of genesis block somehow.
If you want to test blockhash contract's coming into existence, you need network with `constantinopleForkBlock  > 0`

**Comment by winsvega** [comment]
we could put a contract to the genesis pre state on a stage of test filling.
and we have transition tests for constantinople at block 5

**Comment by pirapira** [comment]
@winsvega an issue about adding the blockhash contract in the pre state of filled tests https://github.com/ethereum/cpp-ethereum/issues/4459

**Comment by pirapira** [comment]
Wow, the PR makes all Constantinople blockchain tests failing.

**Comment by winsvega** [comment]
I guess it is failing because of the empty contracts?

**Comment by pirapira** [comment]
@winsvega it seems like so.

**Comment by pirapira** [comment]
Depends on https://github.com/ethereum/tests/issues/305

**Pull request merged**
