### PR TITLE
Replace Crypto++'s SHA256 (partial)

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by chriseth** [comment]
Can you run a quick performance check on the two?

**Comment by chfast** [comment]
The scrypt version is at least 2x faster than Crypto++ version.

**Comment by chriseth** [comment]
Nice! This also brings sha256 more in line with sha3 and ecrecover: https://gist.github.com/chriseth/4168b56bfe638cae8da1945dd988600b

**Comment by chfast** [comment]
Now SHA256 is taken from secp256k1.

I did noob mistake before testing performance impact of this change. The true performance increase is ~39% for the set of 2 tests from #3632.

**Pull request merged**
