### PR TITLE
Add Circle CI

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by gumb0** [comment]
It doesn't run unit tests?

**Comment by gumb0** [comment]
Ah I see, one of the testeths runs all the rest

**Comment by chfast** [comment]
Yes. We should use ctest for this at some point, but I need to talk about it with @winsvega.

**Comment by winsvega** [comment]
have you checked that ctest works as intended? it's been a while since we used it
the build on Travis still goes

**Comment by chfast** [comment]
No, they do not.

**Pull request merged**
