### PR TITLE
Receipt json in RPC output should have "status" field

### PR DESCRIPTION
**Pull request by LoveULin**
replace field name "statusCode" with "status" in RPC output of receipt json #4583

### CODE REVIEW

**Comment by LoveULin** [comment]
Sure. I simply replaced the `toJS` with `toString`, and cast the `uint8_t` returned from `_t.statusCode()` to `uint16_t`. Please help review. Thank you!!:D @gumb0

**Comment by gumb0** [comment]
It's would be nicer to fix `toString()` itself instead of doing `static_cast<uint16_t>` here two times.
I suggest to add a template specialization for `toString<uint8_t>`

**Comment by gumb0** [comment]
We return incorrect value for receipt's `gasUsed`, I filed a separate issue https://github.com/ethereum/cpp-ethereum/issues/4956
@LoveULin maybe you would like to fix that, too

**Comment by LoveULin** [comment]
OK. I think what you said makes sense. I will fix it as soon as possible.
@gumb0 Yes, I'd like to. I will try to fix that (#4956 ) once I have finished my recent work.

**Comment by gumb0** [comment]
Some tests that use `toString<uint8_t>()` fail now, but they look wrong to me, I will fix them.

**Comment by gumb0** [comment]
@LoveULin  Sorry, pushing to your `develop` branch went wrong, now your `develop` corresponds to upstream `develop`, but your & mine changes are here in the upstream branch, I created a new PR to replace this: https://github.com/ethereum/cpp-ethereum/pull/4957

**Comment by gumb0** [comment]
(git magic would be less confusing to me if you created PR from some your branch other than `develop`)

**Pull request closed without merging**
