### PR TITLE
Build EVM JIT by default

### PR DESCRIPTION
**Pull request by chfast**
Details: #2550

### CODE REVIEW

**Comment by LefterisJP** [comment]
Looks good to me as long as all buildbots pass. And it's so awesome we can now kill all the evmjit buildbots :)

**Comment by chfast** [comment]
All bots green!

**Comment by caktux** [comment]
Even though all checks are green, this will break the PPA builds, and for OSX users that don't have LLVM installed with --HEAD and are not installing from bottled packages...

**Comment by gavofyork** [comment]
is there an alterative to waiting for august for this?

could we disable for mac, disable at compile time if llvm version too long (or disable at runtime if llvm version too low)?

i want as many platforms building with llvm by default asap.

**Comment by caktux** [comment]
Disabling at compile time seems like a good solution; brew bottles should work fine and users that want to build from source (either with brew or not) can follow the instructions, but the PPA would take a little more work. Since LLVM is using its own repo (not a PPA), we can't add it for those builds; but we could just copy the packages in our own PPA instead...

**Comment by chfast** [comment]
Not sure if that answers your questions, but we can make EVMJIT option somehow automatic. If not specified by user cmake can check if correct version of LLVM is available in the system.

**Pull request merged**
