### PR TITLE
Remove options that can be replaced with --all

### LINKED ISSUE #4392: Remove --performance option from testeth, and instead use --all
I wonder if `testeth -t VMTests/vmPerformanceTest -- --all` runs `vmPerformanceTest` or not.  It should.

### LINKED ISSUE #4393: Shall we remove --inputlimits option and instead use --all?
Currently, `testeth --inputlimits` runs vmInputLimitTest but `testeth` does not.  Maybe we can use `-t 'VMTests/vmInputLimitTest' --all` instead of this option.

### PR DESCRIPTION
**Pull request by pirapira**
This PR removes options that can be replaced with `--all`.

Fixes #4392.  Fixes #4393.

### CODE REVIEW

**Comment by winsvega** [comment]
could you combine warning messages from this PR? 
https://github.com/ethereum/cpp-ethereum/pull/4367

**Comment by pirapira** [comment]
@winsvega when one of the PRs is merged, I'll adjust the other.

**Comment by pirapira** [comment]
@winsvega I changed my mind, I'll combine these.

**Comment by pirapira** [comment]
I combined these PRs into this one.

**Comment by pirapira** [comment]
Rebased.

**Pull request merged**
