### PR TITLE
Enable EWASM tests in jsontests

### PR DESCRIPTION
**Pull request by axic**
Depends on https://github.com/ethereum/tests/pull/391

### CODE REVIEW

**Comment by axic** [comment]
Need to add the `stEWASMTests` directory in tests first:

```
Running 1 test case...
unknown location(0): fatal error: in "GeneralStateTests/stEWASMTests": boost::filesystem::filesystem_error: boost::filesystem::directory_iterator::construct: No such file or directory: "/home/builder/project/test/jsontests/GeneralStateTests/stEWASMTests"
/home/builder/project/test/tools/jsontests/StateTests.cpp(212): last checkpoint: "stEWASMTests" fixture ctor

*** 1 failure is detected (7 failures are expected) in the test module "Master Test Suite"
```

**Comment by winsvega** [comment]
what is the tests repo commit for this?

**Comment by axic** [comment]
@winsvega it is mentioned on the top: https://github.com/ethereum/tests/pull/391

**Comment by winsvega** [comment]
I don't get it. that test PR contains one git file and no new test files. 
this cpp PR shows that many test files has been changed. are you sure that this PR is pointing to a correct test branch?

**Comment by axic** [comment]
It is pointing to that commit. Probably the tests here wasn't updated for a while.

**Comment by winsvega** [comment]
looks like it does not point to the test branch or it is a spelling issue
```
unknown location(0): fatal error: in "GeneralStateTests/stEWASMTests": boost::filesystem::filesystem_error: boost::filesystem::directory_iterator::construct: No such file or directory: "/home/travis/build/ethereum/cpp-ethereum/build/../test/jsontests/src/GeneralStateTestsFiller/stEWASMTests"
/home/travis/build/ethereum/cpp-ethereum/test/tools/jsontests/StateTests.cpp(212): last checkpoint: "stEWASMTests" fixture ctor
```

anyway we could add this folder any time. 
the issue now is compiling this PR https://github.com/ethereum/cpp-ethereum/pull/4754

**Comment by axic** [comment]
> this cpp PR shows that many test files has been changed. are you sure that this PR is pointing to a correct test branch?

Probably it doesn't point to the right commit because I have no committer rights to the test repo and cannot create a branch on it. In submodules only branch commits can be referred to.

If you merge the `tests` PR first this can be changed to work properly.

**Comment by axic** [comment]
@winsvega what changes do I need to make on https://github.com/ethereum/tests/pull/391 to have it merged?

**Comment by winsvega** [comment]
do you have any wasm tests? 
let me create a PR on top of develop with those tests, so you could see how it works

**Comment by axic** [comment]
@winsvega https://github.com/ethereum/tests/pull/391 is now mergeable (has the source and the output placeholder directory). The are tests (kept here: https://github.com/ewasm/tests/tree/wasm-tests) but **they should no be merged anytime soon**.

I know how it works now, just need to merge https://github.com/ethereum/tests/pull/391 so that this PR can be merged and form that point on we can finally use the environment variable `EHTEREUM_TEST_PATH`

e.g.:
```
ETHEREUM_TEST_PATH='`pwd`/ewasm-tests`' test/testeth -t GeneralStateTests/stEWASMTests -- --filltests --vm hera --singlenet "Byzantium"
``

**Comment by axic** [comment]
@winsvega exactly 👍

**Comment by winsvega** [comment]
https://github.com/ethereum/tests/pull/401

**Comment by axic** [comment]
@winsvega can you please merge https://github.com/ethereum/tests/pull/391 instead of creating a duplicate PR?

**Comment by winsvega** [comment]
well I can. I created a local test branch so this PR could become green.

**Comment by axic** [comment]
This PR will need to be updated after ethereum/tests has the folder merged. This PR shouldn't point to a branch commit :)

**Comment by winsvega** [comment]
do you really need your PR in test repo to be merged or you ok to just close it? 
you could continue working on test repo branch after cpp PR is merged.

**Comment by winsvega** [comment]
do you have commit rights to the test repo?

**Comment by axic** [comment]
I have opened these two PRs so they can be merged into develop and we can avoid a maintenance hell of maintaing two forks. It would be great merging both.

I do not have any commit rights on tests :)

**Comment by winsvega** [comment]
ok. try it now. you should be able to manage the local testeth branches.
https://github.com/orgs/ethereum/teams/c-write/members

**Comment by winsvega** [comment]
do you really need 391 to be merged? 
cause it will take more time. 
once this PR is green I merge https://github.com/ethereum/tests/pull/401 and close 391 
and this PR will be merged into cpp-develop.

**Comment by axic** [comment]
This PR definitely needs to be rebased (it should not point to a branch commit), I am happy to wait for the CI.

**Comment by winsvega** [comment]
its pointing to 401

**Comment by winsvega** [comment]
Appveyour is failing du to some other bug.

**Comment by axic** [comment]
So can https://github.com/ethereum/tests/pull/391 finally merged?

**Comment by pirapira** [comment]
The AppVeyor failure looks like there are still some deadlocks in cpp-ethereum.

**Comment by axic** [comment]
I'd have liked if @jwasinger can keep his commit in his PR, after all he did the work 😉

**Comment by winsvega** [comment]
@axic  you could now work on ewasm test branch with cpp develop 
`testeth -t GeneralStateTests/stEWASMTests `

**Comment by jwasinger** [comment]
Ah no worries.. it was only 1 line commit

**Pull request merged**
