### PR TITLE
Support static builds.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by chriseth** [comment]
@chfast shall I close this one or does it provide any value?

**Comment by chfast** [comment]
We can merge it, if you want to continue later. What are the current issues?

**Comment by chriseth** [comment]
The current issues are that the binary does not find a library. We can continue later. The main idea was not a static library but just a smaller docker image.

**Comment by axic** [comment]
Can we have this option in Solidity too?

**Comment by chriseth** [comment]
Strangely, solidity works without this option: https://hub.docker.com/r/ethereum/solc/

**Comment by chfast** [comment]
@chriseth Please specify the requirements in a separated issue. I can take it from there (I usually like build tweaks).

**Comment by chriseth** [comment]
@chfast I think we can just continue here: https://github.com/ethereum/cpp-ethereum/issues/3156

**Pull request merged**
