### PR TITLE
fix evmjit build for llvm3.8 - PR for master branch

### PR DESCRIPTION
**Pull request by CJentzsch**
@chfast , please have a look.

### CODE REVIEW

**Comment by CJentzsch** [comment]
fixes https://github.com/ethereum/cpp-ethereum/issues/2876

**Comment by chfast** [comment]
I've checked that. I think it breaks some 3.7 builds. 

Can you make this change conditional? Place unchanged `set(LLVM_LIBS ...)` under `if (LLVM3_7_CONFIG)` and the changed one under `if (LLVM3_8_CONFIG)`.

`llvm-config --libs` tool can be used for that, but I still had problems with passing the output back to cmake reliably. And 3.7 will be released today, so let's make the smallest change needed.

Thanks!

**Comment by chfast** [comment]
You could've placed in a couple of lines earlier. There is the if(LLVM3_7_CONFIG) already.

**Comment by CJentzsch** [comment]
Was their a reason that the this line: https://github.com/ethereum/cpp-ethereum/blob/develop/evmjit/CMakeLists.txt#L46 is before the `set` .
If not I can place it in the if/else if a couple of line above.

**Comment by chfast** [comment]
No reasons for that. It can be moved up.

**Pull request merged**
