### PR TITLE
Critical Section __m512i union

### PR DESCRIPTION
**Pull request by mancoast**
This improves performance using 512bit SIMD instructions

### CODE REVIEW

**Comment by bobsummerwill** [comment]
CC @gcolvin.   Please review, Greg.

Looks good to me, because it's all in \#ifdefs.

**Comment by bobsummerwill** [comment]
Please could you `git push --force` this, to see if you can get a success?   Thanks!

We are up against the TravisCI time-limit.   Annoyingly.

**Comment by chriseth** [comment]
@bobsummerwill please do not ask people to force-push to re-run travis. You can restart individual builds directly in travis. If you force-push, also the successful ones will be restarted.

**Comment by bobsummerwill** [comment]
" If you force-push, also the successful ones will be restarted."

From force pushing just a particular PR?   Really?    That wasn't my understanding.

**Comment by chriseth** [comment]
@bobsummerwill if you force-push (after amending, without it does not have any effect), you create a new commit which has to be re-run.

**Comment by bobsummerwill** [comment]
Right - but only that on that single branch for that single PR, right?

Which also have the side-benefit of retaining multiple sets of logs.

**Pull request merged**
