### PR TITLE
Declare MaxAddress and ZeroAddress as const

### PR DESCRIPTION
**Pull request by pirapira**
I'm now looking into the Metropolis changes.  Let me warm up with trivialities.

### CODE REVIEW

**Comment by chfast** [comment]
I wander if could go with `constexpr` here...

**Comment by pirapira** [comment]
Good idea.  I'll try.

**Comment by pirapira** [comment]
@chfast The constructors of `Address` = `FixedHash` are not so `constexpr`ish.  They use `memcpy` and so to initialize the buffer.

**Comment by chfast** [comment]
If not possible to be done quickly give up. But it would be nice task for refactoring.

**Comment by pirapira** [comment]
I give up for now.

**Pull request merged**
