### PR TITLE
Ignore stack protector warnings in CL header.

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by LefterisJP** [comment]
Tested it and this works. It needs to be merged since https://github.com/ethereum/cpp-ethereum-cmake/pull/37 was merged. Without it we can't build due to warning generated from the stack protector due to the opencl header.

**Comment by debris** [comment]
can we instead use `SYSTEM` flag when including directories? Like [here](https://github.com/ethereum/cpp-ethereum-cmake/blob/df7235ea27e9724151a2b35c4788daf37a74705f/UseEth.cmake#L83)

The change is needed here: https://github.com/ethereum/cpp-ethereum/blob/develop/libethash-cl/CMakeLists.txt#L26

```diff
- target_include_directories(${EXECUTABLE} PUBLIC ${OpenCL_INCLUDE_DIR})
+ target_include_directories(${EXECUTABLE} SYSTEM PUBLIC ${OpenCL_INCLUDE_DIR})
```

**Comment by chfast** [comment]
That looks promising. Thanks. I will check that.

**Comment by chfast** [comment]
Actually, we can't do that. cl.hpp is a C++ wrapper for OpenCL functions, but copied to our repo. There is not include_directories-like statement for that one.

**Comment by LefterisJP** [comment]
I always wondered why don't we use the system's `cl.hpp` header. Maybe we can now switch to them and do that? They should be pesent in all systems.
@gavofyork what do you think about that?

**Pull request merged**
