### PR TITLE
Select x64 platform for Visual Studio if not specified

### PR DESCRIPTION
**Pull request by chfast**
Resolves https://github.com/ethereum/cpp-ethereum/issues/4503.

### CODE REVIEW

**Comment by gumb0** [comment]
I have both VS 2015 and 2017 installed and just `cmake ..` chooses 2017 (and fails)

**Comment by gumb0** [comment]
Ah cmake command for windows didn't change. sorry then

**Comment by gumb0** [comment]
But it still fails
```
C:\dev\cpp-ethereum\build_temp>cmake -G "Visual Studio 14 2015 Win64" ..
-- [cable ] Cable 0.2.2 initialized
CMake Error at CMakeLists.txt:69 (project):
  Generator

    Visual Studio 14 2015 Win64

  does not support platform specification, but platform

    x64

  was specified.


-- Configuring incomplete, errors occurred!
See also "C:/dev/cpp-ethereum/build_temp/CMakeFiles/CMakeOutput.log".
```

**Comment by chfast** [comment]
What CMake version? I think this was added in 3.9.

**Comment by gumb0** [comment]
`cmake version 3.9.3`

**Comment by chfast** [comment]
Did you use it for existing build or a new one?

If causes problems probably not worth it.

**Comment by chfast** [comment]
It seems it also caused full Hunter rebuild...

**Comment by gumb0** [comment]
I made new build directory

**Comment by chfast** [comment]
It was working for me for CMake 3.10 :)

**Pull request closed without merging**
