### PR TITLE
Document test filling

### PR DESCRIPTION
**Pull request by pirapira**
For the coming contributors of Metropolis testing, I'm documenting how to use `testeth` for filling tests.

The choice of document locations follows #3653 .

### CODE REVIEW

**Comment by pirapira** [comment]
Many comments are given there https://github.com/ethereum/cpp-ethereum/commit/3cbd46b38adfaf806b9fc69c4d13298c8faf2130#commitcomment-22381880

Also, not necessarily in this PR:
* [ ] how to setup cpp-ethereum
* [ ] then how to check that everything is working (git clone test repo) set up test path and run a testeth without errors
* [ ] then how to setup solidity lllc  (as it required to compile LLL code in test fillers)
* [ ] then how to create a basic example test in existing test suite stExample
* [ ] then how to make a PR to tests repository
* [ ] and we need user feedback. so to see when people feel stuck and unclear about this instruction

**Comment by pirapira** [comment]
@winsvega I added your comments in the document.

**Comment by winsvega** [comment]
I am about to create testeth docker image. that you could download instead of build steps (~600-800Mb)

**Comment by pirapira** [comment]
@winsvega I'll add that when it's available.

**Comment by pirapira** [comment]
@winsvega I added some description about the docker image.

**Comment by pirapira** [comment]
@winsvega addressed comments.

**Comment by pirapira** [comment]
OK.

**Pull request merged**
