### PR TITLE
Eliminate undefied behavior in RLPStream

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by gavofyork** [comment]
what is undefined about this?

**Comment by chfast** [comment]
`memcpy(0,0,0)` is undefined behavior. And it happens when both RLPStream and the argument _s are empty.

**Comment by gavofyork** [comment]
so that's a particularly braindead part of the standard, but part of the standard it is. did you check to make sure that using this STL magic is no slower than just putting an `if (!_s.empty())` before the `memcpy`?

**Comment by chfast** [comment]
No, I haven't checked that. But the code is smaller.

**Pull request merged**
