### PR TITLE
debug macos [WIP]

### PR DESCRIPTION
**Pull request by winsvega**
save random state test before running the filler.

whenever all tests are running on macos 
this change will save the test filler of randomStateTest so we could see if macOS really fails because of some random code execution issue.

I suggest to merge this PR so we have better chance to hit this bug
this change then will be removed after we solve the issue.

### CODE REVIEW

**Comment by chfast** [comment]
How do you want to access this file?

**Comment by winsvega** [comment]
you right. hmm. then I guess I will have to print out the test filler into cerr.

**Comment by chfast** [comment]
You can upload it as an artifact. Check CircleCI config, it stores `eth`.

**Comment by winsvega** [comment]
how to access the artifact?

**Comment by winsvega** [comment]
gived up. testeth random code support on macos is not neccessary.

**Comment by chfast** [comment]
Please delete branches you don't need any more!!!

**Pull request closed without merging**
